#!/usr/bin/env python3
"""
Rhodawk Core Synthesis Engine.

Response synthesis layer with channel-specific formatting (Telegram plain text,
Discord markdown, Slack Block Kit, Email HTML), template injection for research/code/
error/financial reports, and density optimization.

Copyright (c) 2024-2025 Rhodawk AI. All rights reserved.
"""
import html
import json
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, Dict, List, Any


# -- Configuration ---------------------------------------------------------------


@dataclass
class ChannelConfig:
    """Configuration for a specific output channel."""
    name: str
    max_length: int = 4096
    supports_markdown: bool = False
    supports_html: bool = False
    supports_code_blocks: bool = False
    supports_inline_code: bool = False
    supports_links: bool = True
    supports_images: bool = False
    line_separator: str = "\n"
    section_separator: str = "\n\n"


# -- Channel Definitions ---------------------------------------------------------


CHANNELS = {
    "telegram": ChannelConfig(
        name="telegram",
        max_length=4096,
        supports_markdown=False,
        supports_html=True,
        supports_code_blocks=True,
        supports_inline_code=True,
        supports_links=True,
        supports_images=True,
    ),
    "discord": ChannelConfig(
        name="discord",
        max_length=2000,
        supports_markdown=True,
        supports_code_blocks=True,
        supports_inline_code=True,
        supports_links=True,
        supports_images=True,
    ),
    "slack": ChannelConfig(
        name="slack",
        max_length=3000,
        supports_markdown=True,
        supports_code_blocks=True,
        supports_inline_code=True,
        supports_links=True,
        supports_images=True,
    ),
    "email": ChannelConfig(
        name="email",
        max_length=50000,
        supports_markdown=False,
        supports_html=True,
        supports_code_blocks=True,
        supports_inline_code=True,
        supports_links=True,
        supports_images=True,
    ),
    "plain": ChannelConfig(
        name="plain",
        max_length=8000,
        supports_markdown=False,
        supports_html=False,
        supports_code_blocks=False,
        supports_inline_code=False,
        supports_links=False,
    ),
}


# -- Templates -------------------------------------------------------------------


TEMPLATES = {
    "research": {
        "header": "Research Report: {title}",
        "sections": ["Summary", "Key Findings", "Sources", "Recommendations"],
        "footer": "Generated by Rhodawk AI Hermes88",
    },
    "code_review": {
        "header": "Code Review: {title}",
        "sections": ["Overview", "Issues Found", "Suggestions", "Summary"],
        "footer": "Rhodawk AI Code Analysis",
    },
    "error": {
        "header": "Error Report",
        "sections": ["Error", "Context", "Stack Trace", "Resolution"],
        "footer": "",
    },
    "financial": {
        "header": "Financial Report: {title}",
        "sections": ["Summary", "Revenue", "Expenses", "Projections"],
        "footer": "Rhodawk AI Financial Analysis",
    },
    "security": {
        "header": "Security Audit: {title}",
        "sections": ["Executive Summary", "Vulnerabilities", "Risk Assessment", "Remediation"],
        "footer": "Rhodawk AI Security",
    },
    "status": {
        "header": "Status Update",
        "sections": ["Current State", "Progress", "Blockers", "Next Steps"],
        "footer": "",
    },
    "intel": {
        "header": "Intelligence Brief: {title}",
        "sections": ["Summary", "Analysis", "Implications", "Action Items"],
        "footer": "Rhodawk AI Intelligence",
    },
}


# -- Synthesis Engine ------------------------------------------------------------


class SynthesisEngine:
    """
    Response synthesis engine for formatting output across different channels.

    Handles:
    - Channel-specific formatting (Telegram, Discord, Slack, Email, plain)
    - Template-based report generation
    - Content density optimization (trimming for length limits)
    - Code block formatting
    - Link formatting
    - HTML/Markdown conversion
    """

    def __init__(self, default_channel: str = "telegram"):
        self.default_channel = default_channel
        self.channels = CHANNELS
        self.templates = TEMPLATES
        self._stats = {"total_formatted": 0, "truncations": 0}

    def format_response(self, content: str, channel: Optional[str] = None,
                        template: Optional[str] = None,
                        template_vars: Optional[dict] = None,
                        metadata: Optional[dict] = None) -> str:
        """
        Format a response for the specified channel.

        Args:
            content: Raw content to format
            channel: Target channel name
            template: Optional template name to apply
            template_vars: Variables for template substitution
            metadata: Additional metadata for formatting decisions

        Returns:
            Formatted string ready for the target channel.
        """
        channel = channel or self.default_channel
        config = self.channels.get(channel, self.channels["plain"])
        template_vars = template_vars or {}
        metadata = metadata or {}

        # Apply template if specified
        if template and template in self.templates:
            content = self._apply_template(content, template, template_vars, config)

        # Format for channel
        formatted = self._format_for_channel(content, config)

        # Density optimization (trim to fit)
        if len(formatted) > config.max_length:
            formatted = self._optimize_density(formatted, config)
            self._stats["truncations"] += 1

        self._stats["total_formatted"] += 1
        return formatted

    def format_code(self, code: str, language: str = "",
                    channel: Optional[str] = None) -> str:
        """Format a code block for the specified channel."""
        channel = channel or self.default_channel
        config = self.channels.get(channel, self.channels["plain"])

        if config.supports_code_blocks:
            if channel == "telegram":
                if language:
                    return f"<pre><code class=\"{language}\">{html.escape(code)}</code></pre>"
                return f"<pre>{html.escape(code)}</pre>"
            elif channel in ("discord", "slack"):
                return f"```{language}\n{code}\n```"
            elif channel == "email":
                escaped = html.escape(code)
                return (
                    f'<pre style="background:#1e1e1e;color:#d4d4d4;'
                    f'padding:12px;border-radius:6px;overflow-x:auto;">'
                    f'<code>{escaped}</code></pre>'
                )
        return code

    def format_link(self, text: str, url: str,
                    channel: Optional[str] = None) -> str:
        """Format a hyperlink for the specified channel."""
        channel = channel or self.default_channel
        config = self.channels.get(channel, self.channels["plain"])

        if not config.supports_links:
            return f"{text} ({url})"

        if channel == "telegram":
            return f'<a href="{html.escape(url)}">{html.escape(text)}</a>'
        elif channel in ("discord", "slack"):
            return f"[{text}]({url})"
        elif channel == "email":
            return f'<a href="{html.escape(url)}" style="color:#0066cc;">{html.escape(text)}</a>'
        return f"{text} ({url})"

    def format_list(self, items: List[str], ordered: bool = False,
                    channel: Optional[str] = None) -> str:
        """Format a list for the specified channel."""
        channel = channel or self.default_channel
        config = self.channels.get(channel, self.channels["plain"])

        if channel == "email":
            tag = "ol" if ordered else "ul"
            li_items = "".join(f"<li>{html.escape(item)}</li>" for item in items)
            return f"<{tag}>{li_items}</{tag}>"
        elif channel in ("discord", "slack"):
            if ordered:
                return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))
            return "\n".join(f"- {item}" for item in items)
        elif channel == "telegram":
            if ordered:
                return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))
            return "\n".join(f"\u2022 {item}" for item in items)
        else:
            if ordered:
                return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))
            return "\n".join(f"- {item}" for item in items)

    def format_table(self, headers: List[str], rows: List[List[str]],
                     channel: Optional[str] = None) -> str:
        """Format a table for the specified channel."""
        channel = channel or self.default_channel

        if channel == "email":
            header_cells = "".join(
                f'<th style="padding:8px;border:1px solid #ddd;text-align:left;">'
                f'{html.escape(h)}</th>' for h in headers
            )
            body_rows = ""
            for row in rows:
                cells = "".join(
                    f'<td style="padding:8px;border:1px solid #ddd;">'
                    f'{html.escape(str(c))}</td>' for c in row
                )
                body_rows += f"<tr>{cells}</tr>"
            return (
                f'<table style="border-collapse:collapse;width:100%;">'
                f'<thead><tr>{header_cells}</tr></thead>'
                f'<tbody>{body_rows}</tbody></table>'
            )
        elif channel in ("discord", "slack"):
            # Markdown table
            header_line = "| " + " | ".join(headers) + " |"
            separator = "| " + " | ".join("---" for _ in headers) + " |"
            data_lines = []
            for row in rows:
                data_lines.append("| " + " | ".join(str(c) for c in row) + " |")
            return "\n".join([header_line, separator] + data_lines)
        else:
            # Plain text table
            col_widths = [len(h) for h in headers]
            for row in rows:
                for i, cell in enumerate(row):
                    if i < len(col_widths):
                        col_widths[i] = max(col_widths[i], len(str(cell)))

            header_line = "  ".join(h.ljust(col_widths[i]) for i, h in enumerate(headers))
            separator = "  ".join("-" * w for w in col_widths)
            data_lines = []
            for row in rows:
                data_lines.append("  ".join(
                    str(c).ljust(col_widths[i]) for i, c in enumerate(row) if i < len(col_widths)
                ))
            return "\n".join([header_line, separator] + data_lines)

    def format_error(self, error: str, context: str = "",
                     channel: Optional[str] = None) -> str:
        """Format an error message for the specified channel."""
        channel = channel or self.default_channel

        if channel == "telegram":
            parts = [f"<b>Error:</b> {html.escape(error)}"]
            if context:
                parts.append(f"\n<i>Context:</i> {html.escape(context)}")
            return "\n".join(parts)
        elif channel == "email":
            parts = [
                '<div style="background:#fff0f0;border-left:4px solid #ff0000;padding:12px;">',
                f'<strong>Error:</strong> {html.escape(error)}',
            ]
            if context:
                parts.append(f'<br><em>Context:</em> {html.escape(context)}')
            parts.append('</div>')
            return "".join(parts)
        else:
            parts = [f"**Error:** {error}"]
            if context:
                parts.append(f"*Context:* {context}")
            return "\n".join(parts)

    def format_report(self, title: str, sections: Dict[str, str],
                      template_name: str = "research",
                      channel: Optional[str] = None) -> str:
        """
        Format a structured report with sections.

        Args:
            title: Report title
            sections: Dict of section_name -> content
            template_name: Template to use for structure
            channel: Target channel
        """
        channel = channel or self.default_channel
        config = self.channels.get(channel, self.channels["plain"])
        tmpl = self.templates.get(template_name, self.templates["research"])

        parts = []

        # Header
        header = tmpl["header"].format(title=title)
        parts.append(self._format_header(header, channel))

        # Sections
        for section_name in tmpl["sections"]:
            content = sections.get(section_name, "")
            if content:
                parts.append(self._format_section(section_name, content, channel))

        # Footer
        if tmpl.get("footer"):
            parts.append(self._format_footer(tmpl["footer"], channel))

        result = config.section_separator.join(parts)

        # Trim if needed
        if len(result) > config.max_length:
            result = self._optimize_density(result, config)

        return result

    def _apply_template(self, content: str, template_name: str,
                        vars_dict: dict, config: ChannelConfig) -> str:
        """Apply a template to content."""
        tmpl = self.templates.get(template_name, {})
        header = tmpl.get("header", "").format(**vars_dict) if tmpl.get("header") else ""
        footer = tmpl.get("footer", "")

        parts = []
        if header:
            parts.append(header)
        parts.append(content)
        if footer:
            parts.append(footer)

        return config.section_separator.join(parts)

    def _format_for_channel(self, content: str, config: ChannelConfig) -> str:
        """Apply channel-specific formatting transformations."""
        if config.name == "telegram":
            return self._format_telegram(content)
        elif config.name == "discord":
            return self._format_discord(content)
        elif config.name == "slack":
            return self._format_slack(content)
        elif config.name == "email":
            return self._format_email(content)
        return content

    def _format_telegram(self, content: str) -> str:
        """Format for Telegram (HTML subset)."""
        # Convert markdown bold to HTML bold
        content = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', content)
        # Convert markdown italic to HTML italic
        content = re.sub(r'\*(.+?)\*', r'<i>\1</i>', content)
        # Convert markdown code to HTML code
        content = re.sub(r'`([^`]+)`', r'<code>\1</code>', content)
        return content

    def _format_discord(self, content: str) -> str:
        """Format for Discord (full markdown)."""
        # Discord supports standard markdown, just ensure proper code blocks
        return content

    def _format_slack(self, content: str) -> str:
        """Format for Slack (mrkdwn)."""
        # Convert standard markdown bold to Slack bold
        content = re.sub(r'\*\*(.+?)\*\*', r'*\1*', content)
        # Convert standard markdown italic
        content = re.sub(r'_(.+?)_', r'_\1_', content)
        return content

    def _format_email(self, content: str) -> str:
        """Format for email (HTML)."""
        # Wrap in basic HTML structure
        paragraphs = content.split("\n\n")
        html_parts = []
        for para in paragraphs:
            if para.startswith("<"):
                html_parts.append(para)
            else:
                escaped = html.escape(para).replace("\n", "<br>")
                html_parts.append(f"<p>{escaped}</p>")
        return "\n".join(html_parts)

    def _format_header(self, text: str, channel: str) -> str:
        """Format a header for the channel."""
        if channel == "telegram":
            return f"<b>{html.escape(text)}</b>"
        elif channel == "email":
            return f'<h2 style="color:#333;border-bottom:2px solid #0066cc;padding-bottom:8px;">{html.escape(text)}</h2>'
        elif channel in ("discord", "slack"):
            return f"**{text}**"
        return text.upper()

    def _format_section(self, title: str, content: str, channel: str) -> str:
        """Format a section with title and content."""
        if channel == "telegram":
            return f"<b>{html.escape(title)}</b>\n{content}"
        elif channel == "email":
            return f'<h3 style="color:#555;">{html.escape(title)}</h3><p>{content}</p>'
        elif channel in ("discord", "slack"):
            return f"**{title}**\n{content}"
        return f"{title}\n{'=' * len(title)}\n{content}"

    def _format_footer(self, text: str, channel: str) -> str:
        """Format a footer for the channel."""
        if channel == "telegram":
            return f"<i>{html.escape(text)}</i>"
        elif channel == "email":
            return f'<hr><p style="color:#999;font-size:12px;">{html.escape(text)}</p>'
        elif channel in ("discord", "slack"):
            return f"_{text}_"
        return f"---\n{text}"

    def _optimize_density(self, content: str, config: ChannelConfig) -> str:
        """
        Optimize content to fit within the channel's max length.

        Strategy: progressively remove less important content,
        then truncate with an indicator.
        """
        max_len = config.max_length
        if len(content) <= max_len:
            return content

        # Step 1: Remove extra blank lines
        content = re.sub(r'\n{3,}', '\n\n', content)
        if len(content) <= max_len:
            return content

        # Step 2: Shorten long URLs
        content = re.sub(
            r'(https?://\S{80,})',
            lambda m: m.group(0)[:60] + '...',
            content
        )
        if len(content) <= max_len:
            return content

        # Step 3: Truncate with indicator
        truncation_msg = "\n\n[...truncated]"
        return content[:max_len - len(truncation_msg)] + truncation_msg

    def get_stats(self) -> Dict[str, Any]:
        """Get synthesis engine statistics."""
        return dict(self._stats)

    def get_supported_channels(self) -> List[str]:
        """Get list of supported channel names."""
        return list(self.channels.keys())

    def get_supported_templates(self) -> List[str]:
        """Get list of supported template names."""
        return list(self.templates.keys())
