//! Code complexity analyzer module for rhodawk-tools.
//!
//! Provides approximate cyclomatic complexity analysis by counting
//! branching keywords in source files. Identifies complexity hotspots
//! and provides per-language analysis for Python, TypeScript, Go, and Rust.

use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

/// Directories to skip during analysis.
const SKIP_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
];

/// Report generated by analyzing a project's code complexity.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AnalysisReport {
    /// Number of source files analyzed.
    pub files_analyzed: usize,
    /// Total function/method definitions found.
    pub total_functions: usize,
    /// Total class/struct/interface definitions found.
    pub total_classes: usize,
    /// Average cyclomatic complexity across all files.
    pub avg_complexity: f64,
    /// Maximum cyclomatic complexity found in any single file.
    pub max_complexity: usize,
    /// Top complexity hotspots sorted by score descending.
    pub hotspots: Vec<Hotspot>,
}

/// A complexity hotspot representing a file with high complexity.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Hotspot {
    /// Path to the file.
    pub file: String,
    /// Cyclomatic complexity score for this file.
    pub complexity: usize,
    /// Number of functions defined in this file.
    pub function_count: usize,
    /// Total lines in this file.
    pub line_count: usize,
}

/// Per-file analysis result (internal).
#[derive(Debug, Clone)]
struct FileAnalysis {
    path: String,
    functions: usize,
    classes: usize,
    complexity: usize,
    line_count: usize,
}

/// Analyze a project directory for code complexity and structural metrics.
///
/// Traverses the directory in parallel, analyzing each source file for
/// function/class counts and cyclomatic complexity. Produces a report
/// with top hotspots and aggregate statistics.
///
/// # Arguments
///
/// * `path` - Root directory to analyze
/// * `language_filter` - Optional language name to restrict analysis (e.g., "python")
/// * `json_output` - If true, output JSON; otherwise print human-readable format
///
/// # Returns
///
/// `Ok(())` on success, `Err` with description on failure.
pub fn analyze_project(
    path: &Path,
    language_filter: Option<&str>,
    json_output: bool,
) -> Result<(), String> {
    if !path.exists() {
        return Err(format!("Path does not exist: {}", path.display()));
    }

    let report = build_analysis_report(path, language_filter)?;

    if json_output {
        let json = serde_json::to_string_pretty(&report)
            .map_err(|e| format!("JSON serialization error: {}", e))?;
        println!("{}", json);
    } else {
        print_analysis_table(&report);
    }

    Ok(())
}

/// Build an AnalysisReport for the given directory.
///
/// This function is also used by the stats module to compose reports.
pub fn build_analysis_report(
    path: &Path,
    language_filter: Option<&str>,
) -> Result<AnalysisReport, String> {
    let files: Vec<_> = WalkDir::new(path)
        .into_iter()
        .filter_entry(|e| {
            let name = e.file_name().to_str().unwrap_or("");
            !SKIP_DIRS.contains(&name)
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .filter(|e| {
            let ext = e.path().extension().and_then(|x| x.to_str()).unwrap_or("");
            is_analyzable(ext, language_filter)
        })
        .map(|e| e.path().to_path_buf())
        .collect();

    let analyses: Vec<FileAnalysis> = files
        .par_iter()
        .filter_map(|f| analyze_single_file(f).ok())
        .collect();

    let files_analyzed = analyses.len();
    let total_functions: usize = analyses.iter().map(|a| a.functions).sum();
    let total_classes: usize = analyses.iter().map(|a| a.classes).sum();
    let total_complexity: usize = analyses.iter().map(|a| a.complexity).sum();
    let max_complexity = analyses.iter().map(|a| a.complexity).max().unwrap_or(0);
    let avg_complexity = if files_analyzed > 0 {
        total_complexity as f64 / files_analyzed as f64
    } else {
        0.0
    };

    let mut hotspots: Vec<Hotspot> = analyses
        .iter()
        .map(|a| Hotspot {
            file: a.path.clone(),
            complexity: a.complexity,
            function_count: a.functions,
            line_count: a.line_count,
        })
        .collect();

    hotspots.sort_by(|a, b| b.complexity.cmp(&a.complexity));
    hotspots.truncate(10);

    Ok(AnalysisReport {
        files_analyzed,
        total_functions,
        total_classes,
        avg_complexity,
        max_complexity,
        hotspots,
    })
}

/// Check if a file extension is analyzable, optionally filtered by language.
fn is_analyzable(extension: &str, language_filter: Option<&str>) -> bool {
    let analyzable = matches!(
        extension,
        "py" | "ts" | "tsx" | "js" | "jsx" | "go" | "rs" | "java" | "rb"
    );

    if !analyzable {
        return false;
    }

    if let Some(filter) = language_filter {
        match filter.to_lowercase().as_str() {
            "python" | "py" => extension == "py",
            "typescript" | "ts" => matches!(extension, "ts" | "tsx"),
            "javascript" | "js" => matches!(extension, "js" | "jsx"),
            "go" | "golang" => extension == "go",
            "rust" | "rs" => extension == "rs",
            "java" => extension == "java",
            "ruby" | "rb" => extension == "rb",
            _ => true,
        }
    } else {
        true
    }
}

/// Analyze a single source file for complexity metrics.
fn analyze_single_file(path: &Path) -> Result<FileAnalysis, String> {
    let content = fs::read_to_string(path)
        .map_err(|e| format!("Cannot read {}: {}", path.display(), e))?;

    let extension = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    let path_str = path.to_str().unwrap_or("").to_string();

    let (functions, classes, complexity) = match extension {
        "py" => analyze_python(&content),
        "ts" | "tsx" | "js" | "jsx" => analyze_typescript(&content),
        "go" => analyze_go(&content),
        "rs" => analyze_rust(&content),
        "java" => analyze_java(&content),
        "rb" => analyze_ruby(&content),
        _ => (0, 0, 1),
    };

    let line_count = content.lines().count();

    Ok(FileAnalysis {
        path: path_str,
        functions,
        classes,
        complexity,
        line_count,
    })
}

/// Analyze Python source code for complexity.
///
/// Counts: def, class, if, elif, else, for, while, try, except, with
/// Cyclomatic complexity = 1 + branching keywords
fn analyze_python(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut classes = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('#') {
            continue;
        }
        if trimmed.starts_with("def ") {
            functions += 1;
        }
        if trimmed.starts_with("class ") {
            classes += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("elif ")
            || trimmed.starts_with("else:")
            || trimmed.starts_with("for ")
            || trimmed.starts_with("while ")
            || trimmed.starts_with("try:")
            || trimmed.starts_with("except")
            || trimmed.starts_with("with ")
        {
            branches += 1;
        }
    }

    (functions, classes, 1 + branches)
}

/// Analyze TypeScript/JavaScript source code for complexity.
///
/// Counts: function, class, if, else, for, while, try, catch, switch, case
fn analyze_typescript(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut classes = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") || trimmed.starts_with('*') {
            continue;
        }
        if trimmed.contains("function ") || trimmed.contains("=> ") || trimmed.contains("=>") {
            functions += 1;
        }
        if trimmed.starts_with("class ") || trimmed.contains(" class ") {
            classes += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("if(")
            || trimmed.starts_with("} else")
            || trimmed.starts_with("else ")
            || trimmed.starts_with("for ")
            || trimmed.starts_with("for(")
            || trimmed.starts_with("while ")
            || trimmed.starts_with("while(")
            || trimmed.starts_with("try ")
            || trimmed.starts_with("try{")
            || trimmed.starts_with("catch")
            || trimmed.starts_with("switch ")
            || trimmed.starts_with("switch(")
            || trimmed.starts_with("case ")
        {
            branches += 1;
        }
    }

    (functions, classes, 1 + branches)
}

/// Analyze Go source code for complexity.
///
/// Counts: func, if, else, for, switch, case, select
fn analyze_go(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut structs = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") {
            continue;
        }
        if trimmed.starts_with("func ") {
            functions += 1;
        }
        if trimmed.starts_with("type ") && trimmed.contains("struct") {
            structs += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("} else")
            || trimmed.starts_with("else ")
            || trimmed.starts_with("for ")
            || trimmed.starts_with("switch ")
            || trimmed.starts_with("case ")
            || trimmed.starts_with("select ")
            || trimmed.starts_with("select{")
        {
            branches += 1;
        }
    }

    (functions, structs, 1 + branches)
}

/// Analyze Rust source code for complexity.
///
/// Counts: fn, impl, if, else, for, while, match, loop
fn analyze_rust(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut impls = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") {
            continue;
        }
        if trimmed.contains("fn ") && !trimmed.starts_with("///") {
            functions += 1;
        }
        if trimmed.starts_with("impl ") {
            impls += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("} else")
            || trimmed.starts_with("else ")
            || trimmed.starts_with("for ")
            || trimmed.starts_with("while ")
            || trimmed.starts_with("match ")
            || trimmed.starts_with("loop ")
            || trimmed.starts_with("loop{")
        {
            branches += 1;
        }
    }

    (functions, impls, 1 + branches)
}

/// Analyze Java source code for complexity.
fn analyze_java(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut classes = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("//") || trimmed.starts_with('*') {
            continue;
        }
        if (trimmed.contains("public ") || trimmed.contains("private ") || trimmed.contains("protected "))
            && trimmed.contains('(')
            && !trimmed.contains("class ")
        {
            functions += 1;
        }
        if trimmed.contains("class ") || trimmed.contains("interface ") {
            classes += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("if(")
            || trimmed.starts_with("} else")
            || trimmed.starts_with("for ")
            || trimmed.starts_with("for(")
            || trimmed.starts_with("while ")
            || trimmed.starts_with("while(")
            || trimmed.starts_with("try ")
            || trimmed.starts_with("catch")
            || trimmed.starts_with("switch ")
            || trimmed.starts_with("case ")
        {
            branches += 1;
        }
    }

    (functions, classes, 1 + branches)
}

/// Analyze Ruby source code for complexity.
fn analyze_ruby(content: &str) -> (usize, usize, usize) {
    let mut functions = 0;
    let mut classes = 0;
    let mut branches = 0;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('#') {
            continue;
        }
        if trimmed.starts_with("def ") {
            functions += 1;
        }
        if trimmed.starts_with("class ") || trimmed.starts_with("module ") {
            classes += 1;
        }
        if trimmed.starts_with("if ")
            || trimmed.starts_with("elsif ")
            || trimmed.starts_with("else")
            || trimmed.starts_with("unless ")
            || trimmed.starts_with("while ")
            || trimmed.starts_with("until ")
            || trimmed.starts_with("case ")
            || trimmed.starts_with("when ")
            || trimmed.starts_with("rescue")
        {
            branches += 1;
        }
    }

    (functions, classes, 1 + branches)
}

/// Print a human-readable analysis report.
fn print_analysis_table(report: &AnalysisReport) {
    println!("=== Rhodawk Analysis Report ===");
    println!();
    println!("Files analyzed:     {}", report.files_analyzed);
    println!("Total functions:    {}", report.total_functions);
    println!("Total classes:      {}", report.total_classes);
    println!("Average complexity: {:.2}", report.avg_complexity);
    println!("Max complexity:     {}", report.max_complexity);
    println!();

    if !report.hotspots.is_empty() {
        println!("Top Complexity Hotspots:");
        println!("{:<50} {:>10} {:>10} {:>8}", "File", "Complexity", "Functions", "Lines");
        println!("{}", "-".repeat(82));

        for hotspot in &report.hotspots {
            let display_path = if hotspot.file.len() > 48 {
                format!("...{}", &hotspot.file[hotspot.file.len() - 45..])
            } else {
                hotspot.file.clone()
            };
            println!(
                "{:<50} {:>10} {:>10} {:>8}",
                display_path, hotspot.complexity, hotspot.function_count, hotspot.line_count
            );
        }
    }
}
