//! File scanner module for rhodawk-tools.
//!
//! Provides parallel directory traversal with language detection,
//! line counting, and identification of config/test/dependency files.
//! Uses rayon for parallel processing and walkdir for traversal.

use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

/// Report generated by scanning a directory.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ScanReport {
    /// Total number of files found (excluding skipped directories).
    pub total_files: usize,
    /// Total lines of code across all files.
    pub total_lines: usize,
    /// Per-language statistics mapping language name to stats.
    pub languages: HashMap<String, LanguageStats>,
    /// List of configuration files found.
    pub config_files: Vec<String>,
    /// List of test files found.
    pub test_files: Vec<String>,
    /// List of dependency/manifest files found.
    pub dependency_files: Vec<String>,
}

/// Statistics for a single programming language.
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct LanguageStats {
    /// Number of files in this language.
    pub files: usize,
    /// Total lines (including blank and comments).
    pub lines: usize,
    /// Number of blank lines.
    pub blank_lines: usize,
    /// Number of comment lines (lines starting with // or #).
    pub comment_lines: usize,
}

/// Directories to skip during scanning.
const SKIP_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "__pycache__",
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    "dist",
    "build",
];

/// Dependency file names to detect.
const DEPENDENCY_FILES: &[&str] = &[
    "requirements.txt",
    "package.json",
    "go.mod",
    "Cargo.toml",
    "pom.xml",
    "Gemfile",
    "Pipfile",
    "poetry.lock",
    "package-lock.json",
    "yarn.lock",
    "go.sum",
    "Cargo.lock",
];

/// Scan a directory and produce a comprehensive file report.
///
/// Traverses the directory tree in parallel, skipping common non-source
/// directories (.git, node_modules, etc.). Detects languages by file
/// extension and counts total, blank, and comment lines.
///
/// # Arguments
///
/// * `path` - Root directory to scan
/// * `json_output` - If true, output JSON; otherwise print human-readable table
///
/// # Returns
///
/// `Ok(())` on success, `Err` with description on failure.
pub fn scan_directory(path: &Path, json_output: bool) -> Result<(), String> {
    if !path.exists() {
        return Err(format!("Path does not exist: {}", path.display()));
    }
    if !path.is_dir() {
        return Err(format!("Path is not a directory: {}", path.display()));
    }

    let report = build_scan_report(path)?;

    if json_output {
        let json = serde_json::to_string_pretty(&report)
            .map_err(|e| format!("JSON serialization error: {}", e))?;
        println!("{}", json);
    } else {
        print_scan_table(&report);
    }

    Ok(())
}

/// Build a ScanReport for the given directory path.
///
/// This function is also used by the stats module to compose reports.
pub fn build_scan_report(path: &Path) -> Result<ScanReport, String> {
    let files: Vec<_> = WalkDir::new(path)
        .into_iter()
        .filter_entry(|e| !should_skip(e.file_name().to_str().unwrap_or("")))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .map(|e| e.path().to_path_buf())
        .collect();

    let file_results: Vec<FileInfo> = files
        .par_iter()
        .filter_map(|f| analyze_file(f).ok())
        .collect();

    let mut languages: HashMap<String, LanguageStats> = HashMap::new();
    let mut config_files: Vec<String> = Vec::new();
    let mut test_files: Vec<String> = Vec::new();
    let mut dependency_files: Vec<String> = Vec::new();
    let mut total_lines: usize = 0;

    for info in &file_results {
        total_lines += info.lines;

        if let Some(ref lang) = info.language {
            let entry = languages.entry(lang.clone()).or_default();
            entry.files += 1;
            entry.lines += info.lines;
            entry.blank_lines += info.blank_lines;
            entry.comment_lines += info.comment_lines;
        }

        if info.is_config {
            config_files.push(info.path.clone());
        }
        if info.is_test {
            test_files.push(info.path.clone());
        }
        if info.is_dependency {
            dependency_files.push(info.path.clone());
        }
    }

    Ok(ScanReport {
        total_files: file_results.len(),
        total_lines,
        languages,
        config_files,
        test_files,
        dependency_files,
    })
}

/// Internal structure for per-file analysis results.
struct FileInfo {
    path: String,
    language: Option<String>,
    lines: usize,
    blank_lines: usize,
    comment_lines: usize,
    is_config: bool,
    is_test: bool,
    is_dependency: bool,
}

/// Determine if a directory entry should be skipped.
fn should_skip(name: &str) -> bool {
    SKIP_DIRS.contains(&name)
}

/// Analyze a single file for language, line counts, and classification.
fn analyze_file(path: &Path) -> Result<FileInfo, String> {
    let filename = path.file_name().unwrap_or_default().to_str().unwrap_or("");
    let extension = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    let path_str = path.to_str().unwrap_or("").to_string();

    let language = detect_language(extension);
    let is_config = is_config_file(filename, extension);
    let is_test = is_test_file(&path_str, filename);
    let is_dependency = DEPENDENCY_FILES.contains(&filename);

    let content = fs::read_to_string(path).unwrap_or_default();
    let mut lines: usize = 0;
    let mut blank_lines: usize = 0;
    let mut comment_lines: usize = 0;

    for line in content.lines() {
        lines += 1;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            blank_lines += 1;
        } else if is_comment_line(trimmed, extension) {
            comment_lines += 1;
        }
    }

    Ok(FileInfo {
        path: path_str,
        language,
        lines,
        blank_lines,
        comment_lines,
        is_config,
        is_test,
        is_dependency,
    })
}

/// Detect programming language from file extension.
///
/// Returns `Some(language_name)` for known extensions, `None` for unknown.
fn detect_language(extension: &str) -> Option<String> {
    match extension {
        "py" => Some("Python".to_string()),
        "ts" | "tsx" => Some("TypeScript".to_string()),
        "js" | "jsx" => Some("JavaScript".to_string()),
        "go" => Some("Go".to_string()),
        "rs" => Some("Rust".to_string()),
        "java" => Some("Java".to_string()),
        "rb" => Some("Ruby".to_string()),
        "sh" | "bash" | "zsh" => Some("Shell".to_string()),
        "yaml" | "yml" => Some("YAML".to_string()),
        "json" => Some("JSON".to_string()),
        "md" | "markdown" => Some("Markdown".to_string()),
        "sql" => Some("SQL".to_string()),
        "html" | "htm" => Some("HTML".to_string()),
        "css" | "scss" | "less" => Some("CSS".to_string()),
        "toml" => Some("TOML".to_string()),
        "proto" => Some("Protobuf".to_string()),
        "dockerfile" => Some("Docker".to_string()),
        _ => None,
    }
}

/// Determine if a file is a configuration file.
fn is_config_file(filename: &str, extension: &str) -> bool {
    let config_extensions = ["yaml", "yml", "toml", "ini", "cfg"];
    let config_names = [
        "Dockerfile",
        "Makefile",
        "docker-compose.yml",
        "docker-compose.yaml",
        ".env",
        ".env.example",
        ".gitignore",
        ".dockerignore",
    ];

    config_extensions.contains(&extension)
        || config_names.contains(&filename)
        || filename.starts_with("Dockerfile")
        || filename.starts_with(".")
}

/// Determine if a file is a test file based on path and naming conventions.
fn is_test_file(path: &str, filename: &str) -> bool {
    let test_indicators = ["tests/", "__tests__/", "test/", "spec/"];
    let test_prefixes = ["test_", "Test"];
    let test_suffixes = ["_test.", ".test.", "_spec.", ".spec."];

    for indicator in &test_indicators {
        if path.contains(indicator) {
            return true;
        }
    }

    for prefix in &test_prefixes {
        if filename.starts_with(prefix) {
            return true;
        }
    }

    for suffix in &test_suffixes {
        if filename.contains(suffix) {
            return true;
        }
    }

    false
}

/// Determine if a trimmed line is a comment based on file type.
fn is_comment_line(trimmed: &str, extension: &str) -> bool {
    match extension {
        "py" | "sh" | "bash" | "zsh" | "yaml" | "yml" | "toml" | "rb" => {
            trimmed.starts_with('#')
        }
        "rs" | "ts" | "tsx" | "js" | "jsx" | "go" | "java" | "css" | "scss" => {
            trimmed.starts_with("//") || trimmed.starts_with("/*") || trimmed.starts_with('*')
        }
        "html" | "htm" => trimmed.starts_with("<!--"),
        "sql" => trimmed.starts_with("--") || trimmed.starts_with("/*"),
        _ => trimmed.starts_with('#') || trimmed.starts_with("//"),
    }
}

/// Print a human-readable table of scan results.
fn print_scan_table(report: &ScanReport) {
    println!("=== Rhodawk Scan Report ===");
    println!();
    println!("Total files: {}", report.total_files);
    println!("Total lines: {}", report.total_lines);
    println!();
    println!("{:<15} {:>8} {:>10} {:>8} {:>10}", "Language", "Files", "Lines", "Blank", "Comments");
    println!("{}", "-".repeat(55));

    let mut sorted_langs: Vec<_> = report.languages.iter().collect();
    sorted_langs.sort_by(|a, b| b.1.lines.cmp(&a.1.lines));

    for (lang, stats) in sorted_langs {
        println!(
            "{:<15} {:>8} {:>10} {:>8} {:>10}",
            lang, stats.files, stats.lines, stats.blank_lines, stats.comment_lines
        );
    }

    println!();
    println!("Config files: {}", report.config_files.len());
    println!("Test files: {}", report.test_files.len());
    println!("Dependency files: {}", report.dependency_files.len());
}
