//! Pattern search module for rhodawk-tools.
//!
//! Provides structural code search using regex patterns to find
//! function definitions, class definitions, TODO/FIXME markers,
//! and security-sensitive patterns (hardcoded secrets, tokens, keys).

use rayon::prelude::*;
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

/// Directories to skip during search.
const SKIP_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
];

/// Types of search patterns supported.
#[derive(Debug, Clone, PartialEq)]
pub enum SearchType {
    /// Find function definitions (def, fn, func, function, arrow functions).
    Function,
    /// Find class/struct/interface/trait definitions.
    Class,
    /// Find TODO, FIXME, HACK, XXX, BUG, WARN comments.
    Todo,
    /// Find potential hardcoded secrets (API keys, tokens, passwords).
    Secret,
    /// Use a custom regex pattern provided by the user.
    Custom,
}

impl SearchType {
    /// Parse a search type from a string argument.
    ///
    /// Returns `Custom` for unrecognized types.
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "function" | "fn" | "func" => SearchType::Function,
            "class" | "struct" | "type" => SearchType::Class,
            "todo" | "fixme" | "hack" => SearchType::Todo,
            "secret" | "secrets" | "security" => SearchType::Secret,
            _ => SearchType::Custom,
        }
    }

    /// Get the display name for this search type.
    pub fn display_name(&self) -> &str {
        match self {
            SearchType::Function => "function",
            SearchType::Class => "class",
            SearchType::Todo => "todo",
            SearchType::Secret => "secret",
            SearchType::Custom => "custom",
        }
    }
}

/// Report generated by searching for patterns.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SearchReport {
    /// Total number of matches found.
    pub total_matches: usize,
    /// The pattern or search type used.
    pub search_type: String,
    /// Individual match results.
    pub matches: Vec<SearchMatch>,
}

/// A single search match with location and content.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SearchMatch {
    /// File path where the match was found.
    pub file: String,
    /// Line number (1-based) of the match.
    pub line_number: usize,
    /// The matched line content (trimmed).
    pub content: String,
    /// Type of match (function, class, todo, secret, custom).
    pub match_type: String,
}

/// Search for patterns in a directory tree.
///
/// Supports built-in pattern types (function, class, todo, secret) with
/// language-aware regex patterns, as well as custom user-provided patterns.
/// Results include file path, line number, and matched content.
///
/// # Arguments
///
/// * `path` - Root directory to search
/// * `pattern` - Custom regex pattern (used when search_type is Custom)
/// * `search_type` - Type of search to perform
/// * `json_output` - If true, output JSON; otherwise print matches line by line
///
/// # Returns
///
/// `Ok(())` on success, `Err` with description on failure.
pub fn search_patterns(
    path: &Path,
    pattern: &str,
    search_type: SearchType,
    json_output: bool,
) -> Result<(), String> {
    if !path.exists() {
        return Err(format!("Path does not exist: {}", path.display()));
    }

    let report = build_search_report(path, pattern, &search_type)?;

    if json_output {
        let json = serde_json::to_string_pretty(&report)
            .map_err(|e| format!("JSON serialization error: {}", e))?;
        println!("{}", json);
    } else {
        print_search_results(&report);
    }

    Ok(())
}

/// Build a SearchReport for the given directory and pattern.
///
/// Used internally and also by stats module for secret detection.
pub fn build_search_report(
    path: &Path,
    pattern: &str,
    search_type: &SearchType,
) -> Result<SearchReport, String> {
    let regex = build_regex(pattern, search_type)?;

    let files: Vec<_> = WalkDir::new(path)
        .into_iter()
        .filter_entry(|e| {
            let name = e.file_name().to_str().unwrap_or("");
            !SKIP_DIRS.contains(&name)
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .filter(|e| is_searchable(e.path()))
        .map(|e| e.path().to_path_buf())
        .collect();

    let match_type_name = search_type.display_name().to_string();

    let all_matches: Vec<SearchMatch> = files
        .par_iter()
        .flat_map(|f| search_file(f, &regex, &match_type_name))
        .collect();

    Ok(SearchReport {
        total_matches: all_matches.len(),
        search_type: match_type_name,
        matches: all_matches,
    })
}

/// Build the appropriate regex for the given search type.
fn build_regex(pattern: &str, search_type: &SearchType) -> Result<Regex, String> {
    let pattern_str = match search_type {
        SearchType::Function => {
            r"(^\s*(pub\s+)?(async\s+)?fn\s+|^\s*def\s+|^\s*(export\s+)?(async\s+)?function\s+|^\s*func\s+|=>\s*\{)"
        }
        SearchType::Class => {
            r"(^\s*(pub\s+)?(struct|enum|trait)\s+|^\s*class\s+|^\s*(export\s+)?interface\s+|^\s*type\s+\w+\s+struct)"
        }
        SearchType::Todo => {
            r"(TODO|FIXME|HACK|XXX|BUG|WARN)"
        }
        SearchType::Secret => {
            r"(?i)(aws[_-]?(access[_-]?key|secret)|private[_-]?key|password\s*=\s*['\"][^'\"]+['\"]|secret\s*=\s*['\"][^'\"]+['\"]|token\s*=\s*['\"][^'\"]+['\"]|api[_-]?key\s*=\s*['\"][^'\"]+['\"]|AKIA[A-Z0-9]{16})"
        }
        SearchType::Custom => {
            if pattern.is_empty() {
                return Err("Custom search requires a non-empty --pattern argument".to_string());
            }
            pattern
        }
    };

    Regex::new(pattern_str).map_err(|e| format!("Invalid regex pattern: {}", e))
}

/// Check if a file is searchable (not binary, not too large).
fn is_searchable(path: &Path) -> bool {
    let extension = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    let searchable_extensions = [
        "py", "ts", "tsx", "js", "jsx", "go", "rs", "java", "rb", "sh", "bash",
        "yaml", "yml", "json", "toml", "md", "sql", "html", "css", "scss",
        "env", "cfg", "ini", "txt", "proto", "graphql",
    ];

    let filename = path.file_name().and_then(|f| f.to_str()).unwrap_or("");
    let special_files = [
        "Dockerfile", "Makefile", "Gemfile", "Rakefile", "Vagrantfile",
    ];

    searchable_extensions.contains(&extension) || special_files.contains(&filename)
}

/// Search a single file for regex matches.
fn search_file(path: &Path, regex: &Regex, match_type: &str) -> Vec<SearchMatch> {
    let content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let path_str = path.to_str().unwrap_or("").to_string();
    let mut matches = Vec::new();

    for (idx, line) in content.lines().enumerate() {
        if regex.is_match(line) {
            matches.push(SearchMatch {
                file: path_str.clone(),
                line_number: idx + 1,
                content: line.trim().to_string(),
                match_type: match_type.to_string(),
            });
        }
    }

    matches
}

/// Print search results in human-readable format.
fn print_search_results(report: &SearchReport) {
    println!("=== Rhodawk Search Report ===");
    println!("Search type: {}", report.search_type);
    println!("Total matches: {}", report.total_matches);
    println!();

    if report.matches.is_empty() {
        println!("No matches found.");
        return;
    }

    let mut current_file = String::new();
    for m in &report.matches {
        if m.file != current_file {
            if !current_file.is_empty() {
                println!();
            }
            println!("{}:", m.file);
            current_file = m.file.clone();
        }
        println!("  {}:  {}", m.line_number, m.content);
    }
}

/// Check if a directory contains potential secret patterns.
///
/// Convenience function used by the stats module to determine if
/// secrets are present in the codebase.
pub fn has_secrets(path: &Path) -> bool {
    let report = build_search_report(path, "", &SearchType::Secret);
    match report {
        Ok(r) => r.total_matches > 0,
        Err(_) => false,
    }
}
