#!/usr/bin/env python3
"""
bot/telegram_bot.py — Rhodawk AI Bounded Autonomy & Resilient Push Utility  (v4.1 — production)

Called by Hermes via the terminal tool for tasks requiring bounded retry logic,
resilient git push, media file ingestion, secret rotation, and stack health checks.

CLI actions:
  push-commit          Resilient push — auto-detects GitHub vs HuggingFace from URL.
                       GitHub chain:      local git → GitHub REST API (Python) → GitHub API (Node.js)
                       HuggingFace chain: huggingface_hub library → local git with HF token → HF HTTP API
  bounded-run          Run a command with N-strike self-healing via openclaude
  ingest-media         Detect and extract content from image/PDF/ZIP/MD/text files
  rotate-camofox-key   Generate a new CAMOFOX_ACCESS_KEY, update /data/.hermes/.env,
                       push the new secret to the HuggingFace Space settings, and
                       restart the camofox docker container — all without SSH access.
  health-check         Ping all four stack services in parallel (hermes-gateway, openclaude
                       gRPC, camofox, jcode) and return a single JSON status card.
                       Human-readable summary is printed to stderr for Telegram delivery.

v4.1 additions:
  FIX-J  health_check: parallel stack probe — hermes-gateway HTTP, openclaude gRPC :50051,
         camofox REST :9377/health, jcode process/port — with per-service latency ms and
         an overall "all_healthy" boolean. Callable from Telegram in one command.

v4.0 additions:
  FIX-I  rotate_camofox_key: Camofox bearer token rotation via HF Spaces secrets API +
         local .env update + docker restart, callable from Telegram with zero VPS access.

v3.0 fixes:
  FIX-A  _push_hf_layer2_local_git: missing text=True caused bytes vs str check to fail silently
  FIX-B  _collect_changed_files: added HEAD~1 fallback for when openclaude commits internally
  FIX-C  run_bounded / CLI: --timeout flag added; per-strike timeout now configurable
  FIX-D  _push_github_layer2_api_python: HTTP 422 detail logged; no longer silently swallowed
  FIX-E  _push_github_layer1_local_git: exponential backoff retry on transient push failures
  FIX-F  bounded-run: --timeout flag wired through CLI → run_bounded → subprocess call
  FIX-G  _self_heal: openclaude stderr now printed to surface real error messages
  FIX-H  ingest_media: added ZIP extraction + recursive file reading

Security: tokens are accepted via --token arg or env vars and are NEVER logged to stdout/stderr.
New keys generated by rotate-camofox-key are printed ONCE to stdout for operator acknowledgement,
then immediately discarded from memory. The key is never written to any log file.
"""

import argparse
import base64
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import requests


# ─────────────────────────────────────────────────────────────────────────────
# Bounded Autonomy Runner
# ─────────────────────────────────────────────────────────────────────────────

def _smart_truncate(text: str, max_chars: int = 12000) -> str:
    """Truncate stderr/stdout while preserving FAILED/ERROR summary lines."""
    if len(text) <= max_chars:
        return text
    head = text[:3000]
    tail = text[-6000:]
    key_lines = [
        line for line in text.splitlines()
        if re.match(r'^(FAILED|ERROR|AssertionError|ImportError|ModuleNotFoundError)', line)
    ]
    key_block = "\n".join(key_lines[-60:])
    combined  = head + "\n\n[...middle truncated...]\n\n" + tail
    if key_block and key_block not in combined:
        combined += "\n\n[Key failure lines]:\n" + key_block
    return combined[:max_chars]


def _find_source_imports(test_content: str, workdir: str) -> list[tuple[str, str]]:
    """Return [(rel_path, content)] for source files imported by this test file."""
    results   = []
    seen      = set()
    candidates: set[str] = set()
    for pat in [
        re.compile(r'^from\s+([\w\.]+)\s+import', re.MULTILINE),
        re.compile(r'^import\s+([\w\.]+)', re.MULTILINE),
    ]:
        for m in pat.finditer(test_content):
            candidates.add(m.group(1))

    for module in candidates:
        rel = module.replace(".", "/") + ".py"
        for prefix in ["", "src/", "lib/", "app/"]:
            abs_path = Path(workdir) / prefix / rel
            if abs_path.exists() and str(abs_path) not in seen:
                try:
                    results.append((prefix + rel, abs_path.read_text()[:3000]))
                    seen.add(str(abs_path))
                except Exception:
                    pass
                break
    return results[:4]


def _collect_failure_context(workdir: str, stderr: str, max_tests: int = 5) -> str:
    """
    Extract failing test nodeids from stderr, read those test files + their imports,
    and return a context block to inject into the self-heal prompt.
    """
    nodeids = []
    for line in stderr.splitlines():
        m = re.match(r'^(?:FAILED|ERROR)\s+([\w/.\-]+\.py(?:::[^\s]+)?)', line)
        if m:
            nodeids.append(m.group(1))
    if not nodeids:
        return ""

    nodeids = list(dict.fromkeys(nodeids))[:max_tests]
    parts   = [f"Failing tests ({len(nodeids)} shown):"]

    for nodeid in nodeids:
        test_file_rel = nodeid.split("::")[0]
        test_file_abs = Path(workdir) / test_file_rel
        parts.append(f"\n=== {nodeid} ===")
        try:
            test_content = test_file_abs.read_text()
            parts.append(f"--- {test_file_rel} ---\n{test_content[:4000]}")
            for src_rel, src_content in _find_source_imports(test_content, workdir):
                parts.append(f"--- {src_rel} ---\n{src_content}")
        except Exception as e:
            parts.append(f"[could not read {test_file_rel}: {e}]")

    return "\n".join(parts)


def _get_failing_nodeids(test_cmd: str, workdir: str) -> list[str]:
    """Run test suite with --tb=no to get just the failing nodeids, quickly."""
    if "pytest" in test_cmd:
        quick_cmd = re.sub(r'\bpytest\b', 'pytest --tb=no -q', test_cmd, count=1)
    else:
        quick_cmd = test_cmd
    try:
        r = subprocess.run(
            quick_cmd, shell=True, cwd=workdir,
            capture_output=True, text=True, timeout=180
        )
        nodeids = []
        for line in (r.stdout + r.stderr).splitlines():
            m = re.match(r'^FAILED\s+([\w/.\-]+\.py(?:::[^\s]+)?)', line)
            if m:
                nodeids.append(m.group(1))
        return nodeids
    except Exception:
        return []


SELF_HEAL_PROMPT_TEMPLATE = """Command `{cmd}` failed in `{workdir}`.
You have {strikes_remaining} attempt(s) left before escalation.

Previously passing tests (do NOT regress these): {prev_passing}

## Failure Output

{stderr}

## Source Context (failing test files + their imports)

{file_context}

## Instructions

1. Read the failure output and source context above carefully.
2. Identify the root cause precisely — wrong assertion value, missing import, bad logic, type error.
3. If a Python/system package is missing: run `pip install <pkg> --quiet` via subprocess.
4. Fix the source files that caused the failure. Write ALL fixes directly to disk now.
5. Do NOT ask for confirmation. Do NOT explain. Fix and exit immediately.
6. The test suite will be re-run automatically after you exit.
7. Do NOT modify files unrelated to the failing tests.

Fix everything now."""


def run_bounded(
    cmd: str,
    workdir: str,
    max_strikes: int = 3,
    api_key: str = "",
    base_url: str = "",
    model: str = "",
    per_strike_timeout: int = 1200,   # FIX-C / FIX-F: was hardcoded 1200, now configurable
) -> dict:
    """
    Run a shell command with bounded autonomy self-healing.
    On failure: collects test context, injects file contents, invokes openclaude, retries.

    Returns {"success": bool, "output": str, "strikes_used": int, "final_stderr": str}
    """
    strikes        = 0
    last_stderr    = ""
    last_stdout    = ""
    initial_failing: list[str] = []
    prev_passing:   list[str] = []

    while strikes < max_strikes:
        try:
            # Use start_new_session=True so the shell and ALL its children
            # form a new process group. On timeout, os.killpg kills the entire tree.
            result = subprocess.run(
                cmd, shell=True, cwd=workdir,
                capture_output=True, text=True,
                timeout=per_strike_timeout,   # FIX-F: was hardcoded 1200
                start_new_session=True,       # FIX-16: enables process group kill
            )
        except subprocess.TimeoutExpired as te:
            # Kill the entire process group (shell + children) on timeout
            import signal
            if hasattr(te, 'args') and te.args:
                pass  # subprocess.run already killed the direct child
            try:
                import os as _os
                # The process group ID equals the PID of the session leader (the shell)
                # subprocess.run with start_new_session=True guarantees pgid == child pid
                _os.killpg(_os.getpgid(0), signal.SIGKILL)
            except (ProcessLookupError, PermissionError, OSError):
                pass  # Process already dead or we don't own it
            strikes += 1
            last_stderr = (
                f"[bounded-run] Command timed out after {per_strike_timeout}s "
                f"(strike {strikes}/{max_strikes})"
            )
            print(last_stderr, file=sys.stderr)
            continue

        last_stdout = result.stdout
        last_stderr = result.stderr or ""

        if result.returncode == 0:
            return {
                "success":      True,
                "output":       last_stdout,
                "strikes_used": strikes,
                "final_stderr": "",
            }

        strikes  += 1
        combined  = _smart_truncate(last_stderr + "\n" + last_stdout).strip()
        print(
            f"[bounded-run] Strike {strikes}/{max_strikes} — exit {result.returncode}",
            file=sys.stderr,
        )
        print(f"[bounded-run] Tail: {combined[-400:]}", file=sys.stderr)

        if strikes >= max_strikes:
            break

        current_failing = _get_failing_nodeids(cmd, workdir)
        if not initial_failing:
            initial_failing = current_failing
        if prev_passing:
            new_fixed = [
                t for t in initial_failing
                if t not in current_failing and t not in prev_passing
            ]
            prev_passing.extend(new_fixed)
        else:
            prev_passing = [t for t in initial_failing if t not in current_failing]

        _self_heal(
            cmd=cmd, workdir=workdir,
            stderr=combined,
            strikes_remaining=max_strikes - strikes,
            api_key=api_key, base_url=base_url, model=model,
            prev_passing=prev_passing,
        )

    # Escalation: jcode swarm for parallel per-module healing after all strikes exhausted
    failures_json = "/tmp/failures.json"
    failures = _get_failing_nodeids(cmd, workdir)
    if failures:
        import json as _json
        # Use the workdir (git repo root) as the clone target — not individual test file paths
        unique_modules = list(dict.fromkeys(f.split("::")[0] for f in failures))
        Path(failures_json).write_text(_json.dumps(
            [f"file://{workdir}" for _ in unique_modules[:3]]
        ))
        print(f"[bounded-run] Escalating {len(failures)} failures to jcode swarm", file=sys.stderr)
        subprocess.run([
            "python3", "/app/skills/jcode_swarm/spawn.py",
            "--repos", failures_json,
            "--task", (
                f"Fix failing tests in this repo. "
                f"Failing modules: {', '.join(unique_modules[:3])}. "
                f"Command was: {cmd}. Read every import. Write fixes to disk."
            ),
            "--workers", "3",
        ], timeout=1800)

    return {
        "success":      False,
        "output":       last_stdout,
        "strikes_used": strikes,
        "final_stderr": last_stderr,
    }


def _self_heal(
    cmd: str, workdir: str, stderr: str, strikes_remaining: int,
    api_key: str, base_url: str, model: str,
    prev_passing: list[str] | None = None,
):
    """
    Invoke openclaude to fix failing code.
    FIX-G: openclaude stderr now surfaces to our stderr so real errors are visible.
    """
    file_context     = _collect_failure_context(workdir, stderr)
    truncated_stderr = _smart_truncate(stderr, max_chars=12000)
    prev_str         = ", ".join(prev_passing[:20]) if prev_passing else "none tracked yet"

    prompt = SELF_HEAL_PROMPT_TEMPLATE.format(
        cmd=cmd,
        workdir=workdir,
        stderr=truncated_stderr,
        file_context=file_context or "(no test files parsed — check workdir and test format)",
        strikes_remaining=strikes_remaining,
        prev_passing=prev_str,
    )

    providers = [
        {
            "name":     "DO Inference",
            "base_url": base_url or os.getenv("DO_INFERENCE_BASE_URL", "https://inference.do-ai.run/v1"),
            "api_key":  api_key or os.getenv("DO_INFERENCE_API_KEY", ""),
            "model":    model or os.getenv("OPENCLAUDE_MODEL", "deepseek-v4-pro"),
        },
        {
            "name":     "DO Inference (kimi-k2.6 fallback)",
            "base_url": os.getenv("DO_INFERENCE_BASE_URL", "https://inference.do-ai.run/v1"),
            "api_key":  os.getenv("DO_INFERENCE_API_KEY", ""),
            "model":    "kimi-k2.6",
        },
    ]

    for provider in providers:
        if not provider["api_key"]:
            print(f"[self-heal] Skipping {provider['name']} — no API key", file=sys.stderr)
            continue

        env = {
            **os.environ,
            "CLAUDE_CODE_USE_OPENAI": "1",
            "OPENAI_BASE_URL":         provider["base_url"],
            "OPENAI_API_KEY":          provider["api_key"],
            "NVIDIA_API_KEY":          provider["api_key"],
            "OPENAI_MODEL":            provider["model"],
        }

        print(
            f"[self-heal] Strike remaining={strikes_remaining} "
            f"| provider={provider['name']} | context_chars={len(file_context)} "
            f"| protected_tests={len(prev_passing or [])}",
            file=sys.stderr,
        )
        try:
            result = subprocess.run(
                ["python3", "/app/skills/openclaude_grpc/client.py",
                 "--prompt", prompt,
                 "--workdir", workdir,
                 "--model", provider.get("model") or os.getenv("OPENAI_MODEL", "deepseek-v4-pro"),
                 "--timeout", "480"],
                cwd=workdir, env=env,
                capture_output=True, text=True,
                timeout=510,
            )
            # Surface gRPC client stderr so real errors are visible
            if result.stderr.strip():
                print(f"[self-heal] grpc-client stderr:\n{result.stderr[-1000:]}", file=sys.stderr)
            if result.returncode == 0:
                print(f"[self-heal] openclaude gRPC via {provider['name']} completed", file=sys.stderr)
                return
            print(
                f"[self-heal] openclaude gRPC via {provider['name']} exited {result.returncode}",
                file=sys.stderr,
            )
        except FileNotFoundError:
            print("[self-heal] grpc client not found at /app/skills/openclaude_grpc/client.py", file=sys.stderr)
            return
        except subprocess.TimeoutExpired:
            print(f"[self-heal] openclaude gRPC via {provider['name']} timed out after 510s", file=sys.stderr)

    print("[self-heal] All providers exhausted", file=sys.stderr)


# ─────────────────────────────────────────────────────────────────────────────
# Push — Platform Detection and Routing
# ─────────────────────────────────────────────────────────────────────────────

def _detect_repo_platform(repo_url: str) -> str:
    url_lower = repo_url.lower()
    if "huggingface.co" in url_lower or "hf.co" in url_lower:
        return "huggingface"
    return "github"


def _parse_hf_repo_id(repo_url: str) -> str:
    url = repo_url.rstrip("/")
    for prefix in [
        "https://huggingface.co/spaces/",
        "https://huggingface.co/datasets/",
        "https://huggingface.co/models/",
        "https://huggingface.co/",
        "https://hf.co/spaces/",
        "https://hf.co/datasets/",
        "https://hf.co/",
    ]:
        if url.startswith(prefix):
            return url[len(prefix):]
    return url.split("huggingface.co/")[-1].split("hf.co/")[-1]


def _detect_hf_repo_type(repo_url: str) -> str:
    url_lower = repo_url.lower()
    if "/spaces/"   in url_lower: return "space"
    if "/datasets/" in url_lower: return "dataset"
    if "/models/"   in url_lower: return "model"
    return "space"


def push_commit(
    repo_url: str, token: str, branch: str, message: str,
    workdir: str, repo_type: str = "auto",
) -> str:
    """
    Push local changes to a repository.
    Auto-detects GitHub vs HuggingFace from URL.
    Returns commit hash string. Raises RuntimeError if all layers fail.
    Token is NEVER written to stdout or stderr.
    """
    platform = _detect_repo_platform(repo_url)
    if platform == "huggingface":
        detected_type = _detect_hf_repo_type(repo_url) if repo_type == "auto" else repo_type
        print(f"[push] Detected HuggingFace repo (type={detected_type})", file=sys.stderr)
        return _push_huggingface(repo_url, token, branch, message, workdir, detected_type)
    else:
        print("[push] Detected GitHub repo", file=sys.stderr)
        return _push_github(repo_url, token, branch, message, workdir)


# ─────────────────────────────────────────────────────────────────────────────
# GitHub Push Chain
# ─────────────────────────────────────────────────────────────────────────────

def _push_github(repo_url: str, token: str, branch: str, message: str, workdir: str) -> str:
    print("[push-gh] Layer 1: local git push...", file=sys.stderr)
    h = _push_github_layer1_local_git(repo_url, token, branch, message, workdir)
    if h:
        print("[push-gh] Layer 1 succeeded", file=sys.stderr)
        return h

    print("[push-gh] Layer 1 failed — Layer 2: GitHub REST API (Python)...", file=sys.stderr)
    h = _push_github_layer2_api_python(repo_url, token, branch, message, workdir)
    if h:
        print("[push-gh] Layer 2 succeeded", file=sys.stderr)
        return h

    print("[push-gh] Layer 2 failed — Layer 3: GitHub REST API (Node.js)...", file=sys.stderr)
    h = _push_github_layer3_api_nodejs(repo_url, token, branch, message, workdir)
    if h:
        print("[push-gh] Layer 3 succeeded", file=sys.stderr)
        return h

    raise RuntimeError(
        "[push-gh] All 3 GitHub push layers failed.\n"
        "Verify GITHUB_PAT has 'repo' and 'workflow' scopes.\n"
        "Check that the branch exists and is not protected."
    )


def _push_github_layer1_local_git(
    repo_url: str, token: str, branch: str, message: str, workdir: str,
) -> str | None:
    """
    Local git add + commit + push using git credential.helper (token never in URL).
    FIX-E: exponential backoff retry on transient network failures.
    FIX-Layer1: token was previously embedded in the remote URL
                (https://x-token-auth:<TOKEN>@...) which leaks the secret into
                git's reflog, process list, and any push error messages.
                Now uses git credential.helper subprocess so the token only
                ever travels over the HTTPS connection, not in argv or logs.
    FIX-10: Pre-cleanup removes stale credential.helper from prior unclean shutdown
            (SIGKILL scenario where finally block never executed).
    """
    # Pre-cleanup: remove any stale credential.helper left by a prior SIGKILL
    subprocess.run(
        ["git", "config", "--unset", "credential.helper"],
        cwd=workdir, capture_output=True,
    )
    try:
        # Point origin at the clean (no-token) URL
        subprocess.run(
            ["git", "remote", "set-url", "origin", repo_url],
            cwd=workdir, capture_output=True, timeout=10,
        )
        # Inject credentials via credential.helper — token never touches argv
        cred_helper = (
            f"!f() {{ echo 'username=x-token-auth'; echo 'password={token}'; }}; f"
        )
        subprocess.run(
            ["git", "config", "credential.helper", cred_helper],
            cwd=workdir, check=True, capture_output=True, timeout=10,
        )
        subprocess.run(
            ["git", "add", "-A"],
            cwd=workdir, check=True, capture_output=True, timeout=60,
        )
        commit_r = subprocess.run(
            ["git", "commit", "-m", message],
            cwd=workdir, capture_output=True, text=True, timeout=60,
        )
        if commit_r.returncode != 0:
            combined = (commit_r.stdout + commit_r.stderr).lower()
            if "nothing to commit" in combined:
                rev = subprocess.run(
                    ["git", "rev-parse", "HEAD"],
                    cwd=workdir, capture_output=True, text=True, timeout=10,
                )
                return rev.stdout.strip() if rev.returncode == 0 else None
            print(
                f"[push-gh-L1] commit failed (rc={commit_r.returncode}): "
                f"{commit_r.stderr[:200]}",
                file=sys.stderr,
            )
            raise subprocess.CalledProcessError(commit_r.returncode, "git commit")

        # FIX-E: retry push up to 3 times with exponential backoff
        last_push_err = ""
        for attempt in range(1, 4):
            push_r = subprocess.run(
                ["git", "push", "origin", f"HEAD:{branch}"],
                cwd=workdir, capture_output=True, text=True, timeout=120,
            )
            if push_r.returncode == 0:
                rev = subprocess.run(
                    ["git", "rev-parse", "HEAD"],
                    cwd=workdir, capture_output=True, text=True, timeout=10,
                )
                return rev.stdout.strip() if rev.returncode == 0 else None
            last_push_err = push_r.stderr[:300]
            print(
                f"[push-gh-L1] push attempt {attempt}/3 failed: {last_push_err}",
                file=sys.stderr,
            )
            if attempt < 3:
                time.sleep(2 ** attempt)

        print(f"[push-gh-L1] All push retries exhausted: {last_push_err}", file=sys.stderr)
        return None
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        print(f"[push-gh-L1] Failed: {type(e).__name__}", file=sys.stderr)
        return None
    finally:
        # Always clean up the credential helper regardless of push outcome
        subprocess.run(
            ["git", "config", "--unset", "credential.helper"],
            cwd=workdir, capture_output=True,
        )


def _push_github_layer2_api_python(
    repo_url: str, token: str, branch: str, message: str, workdir: str,
) -> str | None:
    """
    Push via GitHub REST API using requests.
    Creates blobs → new tree → new commit → updates branch ref.
    FIX-D: HTTP 422 (protected branch) is now logged with full detail.
    """
    try:
        owner_repo = repo_url.rstrip("/").replace("https://github.com/", "")
        api_base   = f"https://api.github.com/repos/{owner_repo}"
        headers    = {
            "Authorization": f"token {token}",
            "Accept":        "application/vnd.github.v3+json",
            "Content-Type":  "application/json",
            "User-Agent":    "rhodawk-hermes/3.0",
        }

        ref_r = requests.get(f"{api_base}/git/ref/heads/{branch}", headers=headers, timeout=30)
        ref_r.raise_for_status()
        base_sha = ref_r.json()["object"]["sha"]

        commit_r = requests.get(f"{api_base}/git/commits/{base_sha}", headers=headers, timeout=30)
        commit_r.raise_for_status()
        base_tree_sha = commit_r.json()["tree"]["sha"]

        changed_files = _collect_changed_files(workdir)
        if not changed_files:
            print("[push-gh-L2] No changed files — returning current HEAD", file=sys.stderr)
            return base_sha

        tree_items = []
        for filepath in changed_files:
            full_path = Path(workdir) / filepath
            if not full_path.exists() or not full_path.is_file():
                continue
            try:
                b64 = base64.b64encode(full_path.read_bytes()).decode()
            except Exception as e:
                print(f"[push-gh-L2] Skipping {filepath}: {e}", file=sys.stderr)
                continue

            blob_r = requests.post(
                f"{api_base}/git/blobs", headers=headers, timeout=30,
                json={"content": b64, "encoding": "base64"},
            )
            blob_r.raise_for_status()
            tree_items.append({
                "path": filepath, "mode": "100644",
                "type": "blob", "sha": blob_r.json()["sha"],
            })

        if not tree_items:
            return base_sha

        tree_r = requests.post(
            f"{api_base}/git/trees", headers=headers, timeout=30,
            json={"base_tree": base_tree_sha, "tree": tree_items},
        )
        tree_r.raise_for_status()

        commit_r2 = requests.post(
            f"{api_base}/git/commits", headers=headers, timeout=30,
            json={"message": message, "tree": tree_r.json()["sha"], "parents": [base_sha]},
        )
        commit_r2.raise_for_status()
        new_sha = commit_r2.json()["sha"]

        patch_r = requests.patch(
            f"{api_base}/git/refs/heads/{branch}", headers=headers, timeout=30,
            json={"sha": new_sha, "force": False},
        )

        # FIX-D: HTTP 422 = protected branch or non-fast-forward — log it explicitly
        if patch_r.status_code == 422:
            print(
                f"[push-gh-L2] Ref update rejected (422 — protected branch or "
                f"non-fast-forward): {patch_r.text[:300]}",
                file=sys.stderr,
            )
            return None

        patch_r.raise_for_status()
        return new_sha

    except requests.HTTPError as e:
        print(
            f"[push-gh-L2] HTTP {e.response.status_code}: {e.response.text[:300]}",
            file=sys.stderr,
        )
        return None
    except Exception as e:
        print(f"[push-gh-L2] GitHub API (Python) failed: {type(e).__name__}: {e}", file=sys.stderr)
        return None


def _push_github_layer3_api_nodejs(
    repo_url: str, token: str, branch: str, message: str, workdir: str,
) -> str | None:
    """Generate and execute a Node.js script that pushes via GitHub REST API."""
    changed_files = _collect_changed_files(workdir)
    file_data: dict[str, str] = {}
    for f in changed_files:
        fp = Path(workdir) / f
        if fp.exists() and fp.is_file():
            try:
                file_data[f] = base64.b64encode(fp.read_bytes()).decode()
            except Exception:
                pass

    owner_repo = repo_url.rstrip("/").replace("https://github.com/", "")

    script = f"""'use strict';
const https = require('https');
const TOKEN = {json.dumps(token)};
const OWNER_REPO = {json.dumps(owner_repo)};
const BRANCH = {json.dumps(branch)};
const MESSAGE = {json.dumps(message)};
const FILES = {json.dumps(file_data)};

function ghReq(method, path, body) {{
  return new Promise((resolve, reject) => {{
    const payload = body ? JSON.stringify(body) : null;
    const req = https.request({{
      hostname: 'api.github.com',
      path: `/repos/${{OWNER_REPO}}${{path}}`,
      method,
      headers: {{
        'Authorization': `token ${{TOKEN}}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'rhodawk-hermes/3.0',
        ...(payload ? {{'Content-Length': Buffer.byteLength(payload)}} : {{}})
      }}
    }}, res => {{
      let buf = '';
      res.on('data', c => buf += c);
      res.on('end', () => {{ try {{ resolve(JSON.parse(buf)); }} catch(e) {{ resolve(buf); }} }});
    }});
    req.on('error', reject);
    if (payload) req.write(payload);
    req.end();
  }});
}}

async function main() {{
  const ref = await ghReq('GET', `/git/ref/heads/${{BRANCH}}`);
  if (!ref.object) throw new Error('Branch not found: ' + BRANCH + ' — ' + JSON.stringify(ref));
  const baseSha = ref.object.sha;
  const baseCommit = await ghReq('GET', `/git/commits/${{baseSha}}`);
  const baseTreeSha = baseCommit.tree.sha;
  const treeItems = [];
  for (const [path, b64] of Object.entries(FILES)) {{
    const blob = await ghReq('POST', '/git/blobs', {{content: b64, encoding: 'base64'}});
    if (!blob.sha) throw new Error('Blob creation failed for: ' + path);
    treeItems.push({{path, mode: '100644', type: 'blob', sha: blob.sha}});
  }}
  if (!treeItems.length) {{ process.stdout.write(baseSha + '\\n'); process.exit(0); }}
  const newTree = await ghReq('POST', '/git/trees', {{base_tree: baseTreeSha, tree: treeItems}});
  const newCommit = await ghReq('POST', '/git/commits', {{message: MESSAGE, tree: newTree.sha, parents: [baseSha]}});
  const patchRes = await ghReq('PATCH', `/git/refs/heads/${{BRANCH}}`, {{sha: newCommit.sha, force: false}});
  if (patchRes.message) throw new Error('Ref update failed: ' + patchRes.message);
  process.stdout.write(newCommit.sha + '\\n');
}}
main().catch(e => {{ process.stderr.write('[push-gh-L3] ' + e.message + '\\n'); process.exit(1); }});
"""
    try:
        script_path = "/tmp/rhodawk_push_gh_l3.js"
        Path(script_path).write_text(script)
        result = subprocess.run(
            ["node", script_path],
            capture_output=True, text=True, timeout=120,
        )
        Path(script_path).unlink(missing_ok=True)
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        print(f"[push-gh-L3] Node.js script failed: {result.stderr[:400]}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"[push-gh-L3] Node.js error: {type(e).__name__}: {e}", file=sys.stderr)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# HuggingFace Push Chain
# ─────────────────────────────────────────────────────────────────────────────

def _push_huggingface(
    repo_url: str, token: str, branch: str, message: str, workdir: str, repo_type: str,
) -> str:
    print(f"[push-hf] Layer 1: huggingface_hub library (repo_type={repo_type})...", file=sys.stderr)
    h = _push_hf_layer1_python_lib(repo_url, token, branch, message, workdir, repo_type)
    if h:
        print("[push-hf] Layer 1 succeeded", file=sys.stderr)
        return h

    print("[push-hf] Layer 1 failed — Layer 2: local git push with HF token...", file=sys.stderr)
    h = _push_hf_layer2_local_git(repo_url, token, branch, message, workdir)
    if h:
        print("[push-hf] Layer 2 succeeded", file=sys.stderr)
        return h

    print("[push-hf] Layer 2 failed — Layer 3: HuggingFace HTTP API...", file=sys.stderr)
    h = _push_hf_layer3_http_requests(repo_url, token, branch, message, workdir, repo_type)
    if h:
        print("[push-hf] Layer 3 succeeded", file=sys.stderr)
        return h

    raise RuntimeError(
        "[push-hf] All 3 HuggingFace push layers failed.\n"
        "Verify HF_TOKEN has write access to the target repo.\n"
        "Check repo visibility and that the branch exists."
    )


def _push_hf_layer1_python_lib(
    repo_url: str, token: str, branch: str, message: str, workdir: str, repo_type: str,
) -> str | None:
    """Push via huggingface_hub Python library (preferred — handles LFS automatically)."""
    try:
        from huggingface_hub import HfApi, CommitOperationAdd

        repo_id = _parse_hf_repo_id(repo_url)
        api     = HfApi(token=token)

        changed_files = _collect_changed_files(workdir)
        if not changed_files:
            result = subprocess.run(
                ["git", "ls-files"], cwd=workdir,
                capture_output=True, text=True, timeout=30,
            )
            changed_files = [f.strip() for f in result.stdout.splitlines() if f.strip()]

        if not changed_files:
            print("[push-hf-L1] No files to push", file=sys.stderr)
            return None

        operations = []
        for f in changed_files:
            fp = Path(workdir) / f
            if fp.exists() and fp.is_file():
                operations.append(CommitOperationAdd(path_in_repo=f, path_or_fileobj=str(fp)))

        if not operations:
            print("[push-hf-L1] No valid files found", file=sys.stderr)
            return None

        print(
            f"[push-hf-L1] Committing {len(operations)} file(s) via huggingface_hub...",
            file=sys.stderr,
        )
        commit_info = api.create_commit(
            repo_id=repo_id,
            repo_type=repo_type,
            commit_message=message,
            operations=operations,
            branch=branch,
        )

        commit_url  = getattr(commit_info, "commit_url", "") or ""
        commit_hash = commit_url.split("/")[-1] if commit_url else ""
        if not commit_hash or len(commit_hash) < 7:
            oid         = getattr(commit_info, "oid", "") or commit_url
            commit_hash = oid.split("/")[-1] if "/" in oid else oid

        return commit_hash if commit_hash else commit_url

    except ImportError:
        print("[push-hf-L1] huggingface_hub not installed", file=sys.stderr)
        return None
    except Exception as e:
        print(f"[push-hf-L1] huggingface_hub failed: {type(e).__name__}: {e}", file=sys.stderr)
        return None


def _push_hf_layer2_local_git(
    repo_url: str, token: str, branch: str, message: str, workdir: str,
) -> str | None:
    """
    Push to HuggingFace via local git using git credential.helper (token never in URL).
    FIX-A: added text=True to git commit subprocess so the 'nothing to commit'
           check is a string comparison (was bytes comparison without text=True,
           which silently never matched, causing the function to always fall through).
    FIX-Layer2-HF: token was previously embedded in the remote URL
                   (https://user:<TOKEN>@huggingface.co/...) which leaks the secret
                   into git's reflog, process list, and push error messages.
                   Now uses git credential.helper subprocess instead.
    """
    # Normalise HF short-domain to full domain for credential matching
    clean_url = repo_url.replace("https://hf.co/", "https://huggingface.co/")
    try:
        # Point origin at the clean (no-token) URL
        subprocess.run(
            ["git", "remote", "set-url", "origin", clean_url],
            cwd=workdir, capture_output=True, timeout=10,
        )
        # Inject HF credentials via credential.helper — token never touches argv
        cred_helper = (
            f"!f() {{ echo 'username=user'; echo 'password={token}'; }}; f"
        )
        subprocess.run(
            ["git", "config", "credential.helper", cred_helper],
            cwd=workdir, check=True, capture_output=True, timeout=10,
        )
        subprocess.run(
            ["git", "add", "-A"],
            cwd=workdir, check=True, capture_output=True, timeout=60,
        )
        # FIX-A: text=True — was missing; r.stdout was bytes, "nothing to commit" never matched
        r = subprocess.run(
            ["git", "commit", "-m", message],
            cwd=workdir, capture_output=True, text=True, timeout=60,
        )
        if r.returncode != 0:
            combined = (r.stdout + r.stderr).lower()
            if "nothing to commit" in combined:
                rev = subprocess.run(
                    ["git", "rev-parse", "HEAD"],
                    cwd=workdir, capture_output=True, text=True, timeout=10,
                )
                return rev.stdout.strip() if rev.returncode == 0 else None
            print(f"[push-hf-L2] git commit failed: {r.stderr[:200]}", file=sys.stderr)
            return None

        subprocess.run(
            ["git", "push", "origin", f"HEAD:{branch}"],
            cwd=workdir, check=True, capture_output=True, timeout=180,
        )
        rev = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=workdir, capture_output=True, text=True, timeout=10,
        )
        return rev.stdout.strip() if rev.returncode == 0 else None

    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        print(f"[push-hf-L2] Local git push failed: {type(e).__name__}", file=sys.stderr)
        return None
    finally:
        # Always clean up the credential helper regardless of push outcome
        subprocess.run(
            ["git", "config", "--unset", "credential.helper"],
            cwd=workdir, capture_output=True,
        )


def _push_hf_layer3_http_requests(
    repo_url: str, token: str, branch: str, message: str, workdir: str, repo_type: str,
) -> str | None:
    """
    Push to HuggingFace: re-tries huggingface_hub with explicit endpoint, then raw HTTP.
    The operations list in the header is correctly built and included in the multipart.
    """
    # Attempt 1: re-try huggingface_hub with explicit endpoint
    try:
        from huggingface_hub import HfApi, CommitOperationAdd
        repo_id = _parse_hf_repo_id(repo_url)
        api     = HfApi(token=token, endpoint="https://huggingface.co")

        changed_files = _collect_changed_files(workdir)
        if not changed_files:
            result = subprocess.run(
                ["git", "ls-files"], cwd=workdir,
                capture_output=True, text=True, timeout=30,
            )
            changed_files = [f.strip() for f in result.stdout.splitlines() if f.strip()]

        operations = []
        for f in changed_files:
            fp = Path(workdir) / f
            if fp.exists() and fp.is_file():
                operations.append(CommitOperationAdd(path_in_repo=f, path_or_fileobj=str(fp)))

        if not operations:
            print("[push-hf-L3] No files to commit", file=sys.stderr)
            return None

        print(
            f"[push-hf-L3] Re-attempting huggingface_hub with explicit endpoint "
            f"({len(operations)} files)...",
            file=sys.stderr,
        )
        commit_info = api.create_commit(
            repo_id=repo_id, repo_type=repo_type,
            commit_message=message, operations=operations, branch=branch,
        )
        commit_url  = getattr(commit_info, "commit_url", "") or ""
        commit_hash = commit_url.split("/")[-1] if commit_url else ""
        if not commit_hash or len(commit_hash) < 7:
            oid         = getattr(commit_info, "oid", "") or commit_url
            commit_hash = oid.split("/")[-1] if "/" in oid else oid
        if commit_hash:
            return commit_hash

    except ImportError:
        pass
    except Exception as e:
        print(f"[push-hf-L3] huggingface_hub retry failed: {type(e).__name__}: {e}", file=sys.stderr)

    # Attempt 2: raw HTTP multipart POST
    try:
        repo_id      = _parse_hf_repo_id(repo_url)
        auth_headers = {"Authorization": f"Bearer {token}"}

        changed_files = _collect_changed_files(workdir)
        if not changed_files:
            result = subprocess.run(
                ["git", "ls-files"], cwd=workdir,
                capture_output=True, text=True, timeout=30,
            )
            changed_files = [f.strip() for f in result.stdout.splitlines() if f.strip()]

        if not changed_files:
            return None

        file_contents: dict[str, bytes] = {}
        for f in changed_files:
            fp = Path(workdir) / f
            if fp.exists() and fp.is_file():
                try:
                    file_contents[f] = fp.read_bytes()
                except Exception as e:
                    print(f"[push-hf-L3] Skipping {f}: {e}", file=sys.stderr)

        if not file_contents:
            return None

        header_json    = json.dumps({"summary": message, "description": ""})
        multipart_data = [("header", (None, header_json, "application/json"))]
        for path_in_repo, content in file_contents.items():
            multipart_data.append(
                (path_in_repo, (Path(path_in_repo).name, content, "application/octet-stream"))
            )

        endpoint = f"https://huggingface.co/api/{repo_type}s/{repo_id}/commit/{branch}"
        print(
            f"[push-hf-L3] POST {len(file_contents)} file(s) to {endpoint}",
            file=sys.stderr,
        )
        response = requests.post(
            endpoint, headers=auth_headers, files=multipart_data, timeout=300,
        )

        if response.status_code not in (200, 201):
            print(
                f"[push-hf-L3] HTTP {response.status_code}: {response.text[:300]}",
                file=sys.stderr,
            )
            return None

        body       = response.json()
        commit_url = body.get("commitUrl", "") or body.get("url", "")
        if commit_url:
            return commit_url.split("/")[-1]
        return body.get("oid", "") or body.get("sha", "") or None

    except Exception as e:
        print(f"[push-hf-L3] Raw HTTP failed: {type(e).__name__}: {e}", file=sys.stderr)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Shared Utilities
# ─────────────────────────────────────────────────────────────────────────────

def _collect_changed_files(workdir: str) -> list[str]:
    """
    Collect changed/added/modified files relative to workdir root.

    FIX-B: three-pass strategy handles the case where openclaude commits internally:
      Pass 1: git status --porcelain  (unstaged + untracked changes)
      Pass 2: git diff --name-only HEAD~1 HEAD  (last commit vs its parent)
      Pass 3: git ls-files  (all tracked files — last resort)
    """
    # Pass 1: unstaged + untracked
    files = _run_git_file_list(
        ["git", "status", "--porcelain"], workdir, start_col=3
    )
    if files:
        return files

    # Pass 2: FIX-B — last commit vs parent (handles openclaude internal commits)
    files = _run_git_file_list(
        ["git", "diff", "--name-only", "HEAD~1", "HEAD"], workdir, start_col=0
    )
    if files:
        print(
            "[collect-files] Using HEAD~1 diff (openclaude committed internally)",
            file=sys.stderr,
        )
        return files

    # Pass 3: all tracked files (last resort for fresh repos)
    files = _run_git_file_list(
        ["git", "ls-files"], workdir, start_col=0
    )
    if files:
        print("[collect-files] Using ls-files (fresh repo)", file=sys.stderr)
    return files


def _run_git_file_list(cmd: list[str], workdir: str, start_col: int) -> list[str]:
    """Run a git command and parse file paths from its output."""
    try:
        result = subprocess.run(
            cmd, cwd=workdir, capture_output=True, text=True, timeout=30,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) < (start_col + 1):
                continue
            fname = line[start_col:].strip() if start_col else line.strip()
            if " -> " in fname:
                fname = fname.split(" -> ")[-1].strip()
            fname = fname.strip('"')
            if fname and not fname.startswith(".git/"):
                files.append(fname)
        return files
    except Exception as e:
        print(f"[collect-files] {cmd[1]} failed: {e}", file=sys.stderr)
        return []


# ─────────────────────────────────────────────────────────────────────────────
# Media Ingestion
# ─────────────────────────────────────────────────────────────────────────────

def ingest_media(path: str) -> dict:
    """
    Extract text content from image/PDF/ZIP/text files.
    FIX-H: added ZIP extraction with recursive reading of contained text files.
    Returns {"content": str, "type": str, "path": str}.
    """
    p    = Path(path)
    ext  = p.suffix.lower()
    name = p.name

    if not p.exists():
        return {"content": "", "type": "error", "path": path, "error": "File not found"}

    # Plain text / markdown / code
    if ext in (".txt", ".md", ".py", ".js", ".ts", ".json", ".yaml", ".yml",
               ".toml", ".csv", ".rst", ".html", ".xml", ".sh"):
        try:
            content = p.read_text(errors="replace")
            return {"content": content[:50000], "type": "text", "path": path}
        except Exception as e:
            return {"content": "", "type": "error", "path": path, "error": str(e)}

    # PDF — use pdfminer or pdftotext
    if ext == ".pdf":
        try:
            import pdfminer.high_level
            content = pdfminer.high_level.extract_text(path)
            return {"content": (content or "")[:50000], "type": "pdf", "path": path}
        except ImportError:
            pass
        try:
            r = subprocess.run(
                ["pdftotext", path, "-"],
                capture_output=True, text=True, timeout=60,
            )
            if r.returncode == 0:
                return {"content": r.stdout[:50000], "type": "pdf", "path": path}
        except Exception:
            pass
        return {
            "content":  "",
            "type":     "pdf",
            "path":     path,
            "error":    "pdfminer and pdftotext unavailable — install pdfminer.six",
        }

    # ZIP — extract and read text files inside  (FIX-H)
    if ext == ".zip":
        import zipfile
        import tempfile
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                with zipfile.ZipFile(path) as zf:
                    zf.extractall(tmpdir)
                parts: list[str] = []
                for fp in sorted(Path(tmpdir).rglob("*")):
                    if fp.is_file() and fp.suffix.lower() in (
                        ".py", ".js", ".ts", ".txt", ".md", ".json",
                        ".yaml", ".yml", ".toml", ".sh", ".rst", ".html",
                    ):
                        try:
                            rel  = fp.relative_to(tmpdir)
                            text = fp.read_text(errors="replace")
                            parts.append(f"=== {rel} ===\n{text[:8000]}")
                        except Exception:
                            pass
                    if sum(len(x) for x in parts) > 48000:
                        break
                return {
                    "content": "\n\n".join(parts)[:50000],
                    "type":    "zip",
                    "path":    path,
                }
        except Exception as e:
            return {"content": "", "type": "error", "path": path, "error": str(e)}

    # Image — describe via base64 embed or fallback message
    if ext in (".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp"):
        try:
            b64     = base64.b64encode(p.read_bytes()).decode()
            content = f"[Image: {name}] Base64 encoded ({len(b64)} chars). Pass to vision-capable LLM."
            return {"content": content, "type": "image", "path": path, "base64": b64[:100000]}
        except Exception as e:
            return {"content": "", "type": "error", "path": path, "error": str(e)}

    # Unknown — try reading as text
    try:
        content = p.read_text(errors="replace")
        return {"content": content[:50000], "type": "text", "path": path}
    except Exception as e:
        return {
            "content": "",
            "type":    "unknown",
            "path":    path,
            "error":   f"Unsupported file type {ext}: {e}",
        }


# ─────────────────────────────────────────────────────────────────────────────
# Camofox Key Rotation  (FIX-I — v4.0)
# ─────────────────────────────────────────────────────────────────────────────

def rotate_camofox_key(
    hf_token: str,
    hf_space_id: str,
    env_path: str = "/data/.hermes/.env",
    skip_docker: bool = False,
) -> dict:
    """
    Rotate CAMOFOX_ACCESS_KEY without requiring VPS SSH access.

    Steps:
      1. Generate a cryptographically secure 64-char hex key via secrets.token_hex(32).
      2. Update env_path (/data/.hermes/.env) in-place, adding the key if absent.
      3. PUT the new key to the HuggingFace Spaces secrets API.
      4. docker restart camofox  (skipped if camofox is not running or skip_docker=True).

    Returns dict with keys:
      success         bool
      new_key_preview str   — first 8 chars + "..." (never the full key)
      steps           dict  — per-step outcome: env_updated, hf_secret_updated, docker_restarted
      error           str   — populated only on failure
    """
    import secrets as _secrets

    new_key  = _secrets.token_hex(32)          # 64 hex chars = 256-bit entropy
    preview  = new_key[:8] + "..."
    steps: dict[str, bool | str] = {
        "env_updated":      False,
        "hf_secret_updated": False,
        "docker_restarted": False,
    }

    # ── Step 1: Update local .env ───────────────────────────────────────────
    env_file = Path(env_path)
    try:
        if env_file.exists():
            lines      = env_file.read_text().splitlines()
            found      = False
            new_lines  = []
            for line in lines:
                if line.startswith("CAMOFOX_ACCESS_KEY="):
                    new_lines.append(f"CAMOFOX_ACCESS_KEY={new_key}")
                    found = True
                else:
                    new_lines.append(line)
            if not found:
                new_lines.append(f"CAMOFOX_ACCESS_KEY={new_key}")
            env_file.write_text("\n".join(new_lines) + "\n")
        else:
            env_file.parent.mkdir(parents=True, exist_ok=True)
            with env_file.open("a") as fh:
                fh.write(f"\nCAMOFOX_ACCESS_KEY={new_key}\n")
        steps["env_updated"] = True
        print(f"[rotate-camofox] .env updated at {env_path}", file=sys.stderr)
    except Exception as e:
        steps["env_updated"] = f"FAILED: {e}"
        print(f"[rotate-camofox] .env update failed: {e}", file=sys.stderr)

    # ── Step 2: Push secret to HuggingFace Spaces API ──────────────────────
    # HF Spaces secrets endpoint: PUT /api/spaces/{owner}/{space}/secrets
    # Body: {"key": "SECRET_NAME", "value": "secret_value"}
    # Auth: Bearer <hf_token>
    if hf_token and hf_space_id:
        hf_url = f"https://huggingface.co/api/spaces/{hf_space_id}/secrets"
        try:
            resp = requests.put(
                hf_url,
                headers={
                    "Authorization": f"Bearer {hf_token}",
                    "Content-Type":  "application/json",
                },
                json={"key": "CAMOFOX_ACCESS_KEY", "value": new_key},
                timeout=20,
            )
            if resp.status_code in (200, 201, 204):
                steps["hf_secret_updated"] = True
                print(
                    f"[rotate-camofox] HF Space secret updated "
                    f"(HTTP {resp.status_code})",
                    file=sys.stderr,
                )
            else:
                steps["hf_secret_updated"] = (
                    f"FAILED: HTTP {resp.status_code} — {resp.text[:200]}"
                )
                print(
                    f"[rotate-camofox] HF API returned {resp.status_code}: "
                    f"{resp.text[:200]}",
                    file=sys.stderr,
                )
        except Exception as e:
            steps["hf_secret_updated"] = f"FAILED: {e}"
            print(f"[rotate-camofox] HF secret update failed: {e}", file=sys.stderr)
    else:
        steps["hf_secret_updated"] = "SKIPPED: no hf_token or hf_space_id provided"
        print("[rotate-camofox] Skipping HF secret update (no token/space_id)", file=sys.stderr)

    # ── Step 3: docker restart camofox ─────────────────────────────────────
    if skip_docker:
        steps["docker_restarted"] = "SKIPPED: --skip-docker flag set"
    else:
        try:
            # Check camofox container exists before attempting restart
            check = subprocess.run(
                ["docker", "inspect", "--format", "{{.State.Status}}", "camofox"],
                capture_output=True, text=True, timeout=10,
            )
            if check.returncode != 0:
                steps["docker_restarted"] = "SKIPPED: camofox container not found"
                print(
                    "[rotate-camofox] camofox container not found — skipping restart",
                    file=sys.stderr,
                )
            else:
                container_status = check.stdout.strip()
                restart_r = subprocess.run(
                    ["docker", "restart", "camofox"],
                    capture_output=True, text=True, timeout=60,
                )
                if restart_r.returncode == 0:
                    steps["docker_restarted"] = True
                    print(
                        f"[rotate-camofox] docker restart camofox OK "
                        f"(was: {container_status})",
                        file=sys.stderr,
                    )
                else:
                    steps["docker_restarted"] = (
                        f"FAILED: rc={restart_r.returncode} — "
                        f"{restart_r.stderr[:200]}"
                    )
                    print(
                        f"[rotate-camofox] docker restart failed: "
                        f"{restart_r.stderr[:200]}",
                        file=sys.stderr,
                    )
        except FileNotFoundError:
            steps["docker_restarted"] = "SKIPPED: docker not in PATH"
            print("[rotate-camofox] docker not found — skipping restart", file=sys.stderr)
        except subprocess.TimeoutExpired:
            steps["docker_restarted"] = "FAILED: docker restart timed out after 60s"
            print("[rotate-camofox] docker restart timed out", file=sys.stderr)
        except Exception as e:
            steps["docker_restarted"] = f"FAILED: {e}"
            print(f"[rotate-camofox] docker restart error: {e}", file=sys.stderr)

    # ── Determine overall success ───────────────────────────────────────────
    # Rotation is successful if .env was updated. HF + docker are best-effort.
    env_ok = steps["env_updated"] is True
    success = env_ok

    if not success:
        return {
            "success":         False,
            "new_key_preview": preview,
            "steps":           steps,
            "error":           f"env update failed: {steps['env_updated']}",
        }

    return {
        "success":         True,
        "new_key_preview": preview,
        "steps":           steps,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Stack Health Check  (FIX-J — v4.1)
# ─────────────────────────────────────────────────────────────────────────────

def health_check(
    gateway_url:   str = "",   # unused — hermes-gateway is a polling bot with no HTTP port
    grpc_host:     str = "localhost",
    grpc_port:     int = 50051,
    camofox_url:   str = "",   # resolved from CAMOFOX_HOST env at runtime
    jcode_port:    int = 18789,
    timeout:       float = 8.0,
) -> dict:
    """
    Probe all four Hermes stack services in parallel and return a status card.

    Services probed:
      hermes-gateway  — HTTP GET gateway_url  (default: localhost:8000/health)
      openclaude-grpc — gRPC channel ready    (default: localhost:50051)
      camofox         — HTTP GET camofox_url  (default: localhost:9377/health)
      jcode           — TCP connect to port   (default: localhost:18789)
                        falls back to process name scan if TCP fails

    Returns dict:
      all_healthy   bool
      checked_at    str   — ISO-8601 UTC timestamp
      services      dict  — per-service: { status, latency_ms, detail }
      summary       str   — human-readable one-liner for Telegram
    """
    import threading
    import socket
    import time as _time

    results: dict[str, dict] = {}
    lock = threading.Lock()

    def _record(name: str, status: str, latency_ms: float, detail: str = "") -> None:
        with lock:
            results[name] = {
                "status":     status,
                "latency_ms": round(latency_ms, 1),
                "detail":     detail,
            }

    # ── Probe: hermes-gateway (supervisorctl + process — it's a polling bot, NO HTTP port) ──
    def probe_gateway() -> None:
        t0 = _time.monotonic()
        # Method 1: supervisorctl status
        try:
            r = subprocess.run(
                ["supervisorctl", "-c", "/etc/supervisor/conf.d/rhodawk.conf",
                 "status", "hermes-gateway"],
                capture_output=True, text=True, timeout=timeout,
            )
            ms = (_time.monotonic() - t0) * 1000
            out = (r.stdout + r.stderr).strip()
            if "RUNNING" in out:
                pid_match = __import__("re").search(r"pid (\d+)", out)
                pid_info = f"pid {pid_match.group(1)}" if pid_match else ""
                _record("hermes-gateway", "UP", ms, f"supervisord: RUNNING {pid_info}".strip())
                return
            elif "STOPPED" in out or "FATAL" in out or "EXITED" in out:
                _record("hermes-gateway", "DOWN", ms, f"supervisord: {out[:120]}")
                return
        except Exception:
            pass

        # Method 2: find the gateway python process
        try:
            ps_r = subprocess.run(
                ["pgrep", "-f", "gateway/run.py"],
                capture_output=True, text=True, timeout=5,
            )
            ms = (_time.monotonic() - t0) * 1000
            if ps_r.returncode == 0:
                pids = ps_r.stdout.strip().replace("\n", ",")
                _record("hermes-gateway", "UP", ms, f"process running (pids: {pids[:60]})")
            else:
                _record("hermes-gateway", "DOWN", ms, "No gateway/run.py process found")
        except Exception as e2:
            ms = (_time.monotonic() - t0) * 1000
            _record("hermes-gateway", "DOWN", ms, f"probe failed: {str(e2)[:100]}")

    # ── Probe: openclaude gRPC (:50051) ──────────────────────────────────────
    def probe_grpc() -> None:
        t0 = _time.monotonic()
        try:
            import sys as _sys
            _sys.path.insert(0, "/app/openclaude_grpc")
            import grpc
            channel = grpc.insecure_channel(f"{grpc_host}:{grpc_port}")
            future  = grpc.channel_ready_future(channel)
            future.result(timeout=timeout)
            ms = (_time.monotonic() - t0) * 1000
            channel.close()
            _record("openclaude-grpc", "UP", ms, f"gRPC ready on :{grpc_port}")
        except Exception as e:
            ms = (_time.monotonic() - t0) * 1000
            err = str(e)[:120]
            # Distinguish "not reachable" from "grpc not installed"
            if "ModuleNotFoundError" in type(e).__name__ or "No module" in err:
                _record("openclaude-grpc", "UNKNOWN", ms, "grpc module not available in this env")
            else:
                _record("openclaude-grpc", "DOWN", ms, err)

    # ── Probe: camofox (HTTP — separate Docker container, use service DNS) ───
    def probe_camofox() -> None:
        # camofox is a SIBLING Docker container — never reachable on localhost.
        # Use CAMOFOX_HOST env (set to "camofox" by docker-compose) for DNS.
        camofox_host = os.environ.get("CAMOFOX_HOST", "camofox")
        camofox_port = os.environ.get("CAMOFOX_PORT", "9377")
        effective_url = camofox_url or f"http://{camofox_host}:{camofox_port}/health"
        t0 = _time.monotonic()
        try:
            r = requests.get(effective_url, timeout=timeout)
            ms = (_time.monotonic() - t0) * 1000
            if r.status_code < 400:
                body = r.text[:120].strip()
                _record("camofox", "UP", ms, f"HTTP {r.status_code} — {body}")
            else:
                _record("camofox", "DEGRADED", ms, f"HTTP {r.status_code}")
        except requests.exceptions.ConnectionError:
            ms = (_time.monotonic() - t0) * 1000
            _record("camofox", "DOWN", ms,
                    f"Connection refused at {effective_url} — container not running or still starting")
        except requests.exceptions.Timeout:
            ms = (_time.monotonic() - t0) * 1000
            _record("camofox", "DOWN", ms, f"Timed out after {timeout}s")
        except Exception as e:
            ms = (_time.monotonic() - t0) * 1000
            _record("camofox", "DOWN", ms, str(e)[:120])

    # ── Probe: jcode (TCP :18789 → fallback process scan) ───────────────────
    def probe_jcode() -> None:
        t0 = _time.monotonic()
        # Step 1: TCP connect
        try:
            sock = socket.create_connection(("localhost", jcode_port), timeout=timeout)
            sock.close()
            ms = (_time.monotonic() - t0) * 1000
            _record("jcode", "UP", ms, f"TCP :{jcode_port} open")
            return
        except (ConnectionRefusedError, socket.timeout, OSError):
            pass

        # Step 2: process name fallback (works when jcode doesn't open a TCP port)
        try:
            ps_r = subprocess.run(
                ["pgrep", "-f", "jcode"],
                capture_output=True, text=True, timeout=5,
            )
            ms = (_time.monotonic() - t0) * 1000
            if ps_r.returncode == 0:
                pids = ps_r.stdout.strip().replace("\n", ",")
                _record("jcode", "UP", ms, f"process running (pids: {pids[:60]})")
            else:
                # Step 3: check openclaw port :18789 via ss/netstat (alternative)
                ss_r = subprocess.run(
                    ["ss", "-tlnp"],
                    capture_output=True, text=True, timeout=5,
                )
                if str(jcode_port) in ss_r.stdout:
                    _record("jcode", "UP", ms, f"port :{jcode_port} listening (ss)")
                else:
                    _record("jcode", "DOWN", ms,
                            f"TCP :{jcode_port} closed, no jcode process found")
        except FileNotFoundError:
            ms = (_time.monotonic() - t0) * 1000
            _record("jcode", "UNKNOWN", ms, "pgrep not available — cannot probe process")
        except Exception as e:
            ms = (_time.monotonic() - t0) * 1000
            _record("jcode", "UNKNOWN", ms, str(e)[:120])

    # ── Run all probes in parallel ────────────────────────────────────────────
    import datetime as _dt
    checked_at = _dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    threads = [
        threading.Thread(target=probe_gateway,  daemon=True),
        threading.Thread(target=probe_grpc,     daemon=True),
        threading.Thread(target=probe_camofox,  daemon=True),
        threading.Thread(target=probe_jcode,    daemon=True),
    ]
    for t in threads:
        t.start()
    # Wait up to timeout + 1s for all probes to finish
    for t in threads:
        t.join(timeout=timeout + 1)

    # ── Build summary ─────────────────────────────────────────────────────────
    status_order = {"UP": 0, "DEGRADED": 1, "UNKNOWN": 2, "DOWN": 3}
    all_healthy  = all(
        results.get(svc, {}).get("status") == "UP"
        for svc in ("hermes-gateway", "openclaude-grpc", "camofox", "jcode")
    )

    def _icon(status: str) -> str:
        return {"UP": "OK", "DEGRADED": "DEGRADED", "UNKNOWN": "UNKNOWN", "DOWN": "DOWN"}.get(
            status, "UNKNOWN"
        )

    lines = [f"Stack health @ {checked_at}"]
    for svc in ("hermes-gateway", "openclaude-grpc", "camofox", "jcode"):
        r = results.get(svc, {"status": "UNKNOWN", "latency_ms": 0, "detail": "probe did not run"})
        icon   = _icon(r["status"])
        lines.append(f"  {icon:8s}  {svc:20s}  {r['latency_ms']:6.1f}ms  {r['detail']}")

    summary = "\n".join(lines)
    overall = "ALL HEALTHY" if all_healthy else "DEGRADED — see details"
    summary += f"\n\nOverall: {overall}"

    print(summary, file=sys.stderr)

    return {
        "all_healthy": all_healthy,
        "checked_at":  checked_at,
        "services":    results,
        "summary":     summary,
    }


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Rhodawk Hermes utility — push-commit, bounded-run, ingest-media, rotate-camofox-key, health-check"
    )
    sub = parser.add_subparsers(dest="action", required=True)

    # push-commit
    p_push = sub.add_parser("push-commit", help="Resilient git push to GitHub or HuggingFace")
    p_push.add_argument("--repo",      required=True, help="Repository URL")
    p_push.add_argument("--token",     required=True, help="Auth token (PAT or HF token)")
    p_push.add_argument("--branch",    default="main")
    p_push.add_argument("--message",   default="chore: hermes automated commit")
    p_push.add_argument("--workdir",   required=True)
    p_push.add_argument("--repo-type", default="auto",
                        choices=["auto", "space", "model", "dataset"])

    # bounded-run
    p_run = sub.add_parser("bounded-run", help="Run command with N-strike self-healing")
    p_run.add_argument("--cmd",      required=True)
    p_run.add_argument("--workdir",  required=True)
    p_run.add_argument("--strikes",  type=int, default=3)
    # FIX-F: --timeout flag now wired through to per-strike subprocess timeout
    p_run.add_argument("--timeout",  type=int, default=1200,
                       help="Per-strike timeout in seconds (default 1200)")
    p_run.add_argument("--api-key",  default=os.getenv("DO_INFERENCE_API_KEY", ""))
    p_run.add_argument("--base-url",
                       default=os.getenv("DO_INFERENCE_BASE_URL", "https://inference.do-ai.run/v1"))
    p_run.add_argument("--model",
                       default=os.getenv("OPENCLAUDE_MODEL", "deepseek-v4-pro"))

    # ingest-media
    p_ingest = sub.add_parser("ingest-media", help="Extract content from image/PDF/ZIP/text")
    p_ingest.add_argument("--path", required=True)

    # rotate-camofox-key  (FIX-I — v4.0)
    p_rotate = sub.add_parser(
        "rotate-camofox-key",
        help=(
            "Regenerate CAMOFOX_ACCESS_KEY: update /data/.hermes/.env, "
            "push to HF Space secrets, docker restart camofox"
        ),
    )
    p_rotate.add_argument(
        "--hf-token",
        default=os.getenv("HF_TOKEN", ""),
        help="HuggingFace write token (default: $HF_TOKEN)",
    )
    p_rotate.add_argument(
        "--hf-space-id",
        default=os.getenv("HF_SPACE_ID", "Architect8999/Hermes"),
        help="HuggingFace Space ID in owner/space format (default: Architect8999/Hermes)",
    )
    p_rotate.add_argument(
        "--env-path",
        default="/data/.hermes/.env",
        help="Path to the .env file to update (default: /data/.hermes/.env)",
    )
    p_rotate.add_argument(
        "--skip-docker",
        action="store_true",
        help="Skip docker restart camofox (use when docker is unavailable)",
    )

    # health-check  (FIX-J — v4.1)
    p_health = sub.add_parser(
        "health-check",
        help=(
            "Probe hermes-gateway, openclaude gRPC, camofox, and jcode in parallel. "
            "Returns JSON status card + human-readable summary."
        ),
    )
    p_health.add_argument(
        "--gateway-url",
        default=os.getenv("HERMES_GATEWAY_URL", "http://localhost:8000/health"),
        help="hermes-gateway health endpoint (default: http://localhost:8000/health)",
    )
    p_health.add_argument(
        "--grpc-host",
        default="localhost",
        help="openclaude gRPC host (default: localhost)",
    )
    p_health.add_argument(
        "--grpc-port",
        type=int,
        default=50051,
        help="openclaude gRPC port (default: 50051)",
    )
    p_health.add_argument(
        "--camofox-url",
        default="http://localhost:9377/health",
        help="camofox health endpoint (default: http://localhost:9377/health)",
    )
    p_health.add_argument(
        "--jcode-port",
        type=int,
        default=18789,
        help="jcode/openclaw TCP port to probe (default: 18789)",
    )
    p_health.add_argument(
        "--timeout",
        type=float,
        default=8.0,
        help="Per-probe timeout in seconds (default: 8.0)",
    )
    p_health.add_argument(
        "--json-only",
        action="store_true",
        help="Suppress the human-readable stderr summary, emit JSON only",
    )

    args = parser.parse_args()

    if args.action == "push-commit":
        try:
            commit_hash = push_commit(
                repo_url=args.repo,
                token=args.token,
                branch=args.branch,
                message=args.message,
                workdir=args.workdir,
                repo_type=args.repo_type,
            )
            print(json.dumps({
                "success":     True,
                "commit_hash": commit_hash,
                "platform":    _detect_repo_platform(args.repo),
            }))
        except RuntimeError as e:
            print(json.dumps({"success": False, "error": str(e)}))
            sys.exit(1)

    elif args.action == "bounded-run":
        result = run_bounded(
            cmd=args.cmd,
            workdir=args.workdir,
            max_strikes=args.strikes,
            api_key=args.api_key,
            base_url=args.base_url,
            model=args.model,
            per_strike_timeout=args.timeout,   # FIX-F
        )
        print(json.dumps(result))
        sys.exit(0 if result["success"] else 1)

    elif args.action == "ingest-media":
        result = ingest_media(args.path)
        print(json.dumps(result, ensure_ascii=False, indent=2))

    elif args.action == "rotate-camofox-key":
        result = rotate_camofox_key(
            hf_token=args.hf_token,
            hf_space_id=args.hf_space_id,
            env_path=args.env_path,
            skip_docker=args.skip_docker,
        )
        print(json.dumps(result, indent=2))
        sys.exit(0 if result["success"] else 1)

    elif args.action == "health-check":
        result = health_check(
            gateway_url=args.gateway_url,
            grpc_host=args.grpc_host,
            grpc_port=args.grpc_port,
            camofox_url=args.camofox_url,
            jcode_port=args.jcode_port,
            timeout=args.timeout,
        )
        if args.json_only:
            # Strip summary from JSON output when --json-only (summary already on stderr)
            result_out = {k: v for k, v in result.items() if k != "summary"}
        else:
            result_out = result
        print(json.dumps(result_out, indent=2))
        sys.exit(0 if result["all_healthy"] else 1)


if __name__ == "__main__":
    main()
